#!/usr/bin/env node
/**
 * Ahrefs report (Route A).
 *
 * Usage:
 *   1. Ahrefs paid plan with API access -> generate a token at
 *      https://ahrefs.com/api (or profile > API token)
 *   2. Add to .env (gitignored): AHREFS_API_TOKEN=your_token
 *   3. Run: node scripts/ahrefs-report.mjs
 *
 * Output: seo-reports/ahrefs-YYYY-MM-DD.md (domain summary, new backlinks,
 * top organic keywords) plus a console summary. Endpoints that the current
 * plan does not include fail gracefully and are skipped.
 *
 * Env:
 *   AHREFS_API_TOKEN    required
 *   AHREFS_TARGET       default: labs.techadyant.com
 */
import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import * as path from 'node:path';

const ROOT = path.resolve(process.cwd());
const TARGET = process.env.AHREFS_TARGET || 'labs.techadyant.com';

function loadEnv() {
  for (const f of ['.env', '.env.local']) {
    const p = path.join(ROOT, f);
    if (!existsSync(p)) continue;
    for (const line of readFileSync(p, 'utf8').split('\n')) {
      const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
      if (m) process.env[m[1]] = process.env[m[1]] || m[2].replace(/^["']|["']$/g, '');
    }
  }
}
loadEnv();

const TOKEN = process.env.AHREFS_API_TOKEN;
if (!TOKEN) {
  console.error('Missing AHREFS_API_TOKEN.');
  console.error('Setup:');
  console.error('  1. You need a paid Ahrefs plan (API access is included with paid plans).');
  console.error('  2. Generate a token at https://ahrefs.com/api (or Ahrefs > profile > API token).');
  console.error('  3. Add to the repo .env (already gitignored):  AHREFS_API_TOKEN=<token>');
  process.exit(1);
}

const BASE = 'https://ahrefs.com/v3';
async function call(endpoint, params = {}) {
  const url = `${BASE}/${endpoint}?` + new URLSearchParams({ target: TARGET, ...params });
  const res = await fetch(url, { headers: { Authorization: `Bearer ${TOKEN}`, Accept: 'application/json' } });
  if (res.status === 401 || res.status === 403) throw new Error('Ahrefs auth failed (401/403) - check the token and that API access is enabled on the plan.');
  if (res.status === 429) throw new Error('Ahrefs rate limit hit (429) - wait and retry.');
  if (!res.ok) {
    const t = await res.text().catch(() => '');
    throw new Error(`Ahrefs API ${res.status}: ${t.slice(0, 200)}`);
  }
  return res.json();
}

function mdTable(headers, rows) {
  const fmt = (v, i) => (typeof v === 'number' ? (i === 2 ? (v * 100).toFixed(1) + '%' : Number.isInteger(v) ? v : v.toFixed(1)) : String(v ?? ''));
  const lines = [['| ' + headers.join(' | ') + ' |'], ['|' + headers.map(() => '---').join('|') + '|']];
  for (const r of rows) lines.push('| ' + r.map(fmt).join(' | ') + ' |');
  return lines.join('\n');
}

async function main() {
  const today = new Date().toISOString().slice(0, 10);
  const md = [`# Ahrefs report - ${today}`, '', `**Target:** ${TARGET}`, ''];

  // 1. Domain summary
  try {
    const s = await call('site-explorer/summary', { mode: 'exact', protocol: 'both' });
    const m = s.metrics || s || {};
    const keys = ['domain_rating', 'backlinks', 'referring_domains', 'organic_keywords', 'organic_traffic'];
    const present = keys.filter((k) => m[k] != null);
    md.push('## Domain summary', mdTable(['Metric', 'Value'], present.map((k) => [k.replace(/_/g, ' '), m[k]])), '');
    console.log(`Summary: DR ${m.domain_rating ?? 'n/a'} · ${m.backlinks ?? '?'} backlinks · ${m.referring_domains ?? '?'} referring domains`);
  } catch (e) { md.push('## Domain summary', `_${e.message}_`, ''); console.warn('summary:', e.message); }

  // 2. New backlinks (last 30 days)
  try {
    const b = await call('site-explorer/backlinks/new', { limit: 15 });
    const rows = (b.backlinks || []).map((x) => [x.url_from, x.url_from_title?.slice(0, 60) || '', x.first_seen?.slice(0, 10) || '']);
    md.push(`## New backlinks (total: ${b.meta?.total_new_backlinks ?? rows.length})`, rows.length ? mdTable(['From', 'Title', 'First seen'], rows) : '_None._', '');
    console.log(`New backlinks (30d): ${b.meta?.total_new_backlinks ?? 0}`);
  } catch (e) { md.push('## New backlinks', `_${e.message}_`, ''); console.warn('backlinks:', e.message); }

  // 3. Top organic keywords (plan-dependent)
  try {
    const k = await call('site-explorer/organic-keywords', { limit: 15 });
    const rows = (k.keywords || []).map((x) => [x.keyword, x.position, x.volume, x.traffic]);
    md.push('## Top organic keywords', rows.length ? mdTable(['Keyword', 'Position', 'Volume', 'Traffic'], rows) : '_No keyword data._', '');
    console.log(`Organic keywords: ${k.meta?.total ?? rows.length}`);
  } catch (e) { md.push('## Top organic keywords', `_${e.message}_`, ''); console.warn('keywords:', e.message); }

  md.push(`_Generated by scripts/ahrefs-report.mjs on ${new Date().toISOString()}._`, '');
  const outPath = path.join(ROOT, 'seo-reports', `ahrefs-${today}.md`);
  mkdirSync(path.dirname(outPath), { recursive: true });
  writeFileSync(outPath, md, 'utf8');
  console.log(`Ahrefs report written: ${outPath}`);
}

main().catch((e) => { console.error('\nAhrefs report failed:', e.message); process.exit(1); });
