#!/usr/bin/env python3
"""
Merge duplicate SID company entities (ideaForge, Raphe mPhibr) into their canonical records.

Writes:
  data/sid-maintenance/merge_duplicates_2026-09-30.sql  (run in the n8ndb SQL editor)
and patches, to match what the next bake will export:
  app/research/_atlas.json  (drops the duplicate players, re-points / de-dupes their edges)
  public/_redirects         (retired player URLs -> canonical player page)

The SQL uses the existing sid.merge_entity(keep, drop): it re-points relationships
(deleting ones the survivor already has), keeps the dropped name as an alias of the
survivor, and marks the duplicate status='merged', merged_into=keep, is_watchlist=false.
Idempotent: merge_entity is a no-op on an already-merged row's (now empty) edges.
"""
import json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SQL = os.path.join(ROOT, 'data', 'sid-maintenance', 'merge_duplicates_2026-09-30.sql')
ATLAS = os.path.join(ROOT, 'app', 'research', '_atlas.json')
REDIRECTS = os.path.join(ROOT, 'public', '_redirects')

IDEAFORGE = ('080e8af1-025f-478f-bea8-26082bf32df1', 'ideaForge Technology Limited', 'ideaforge-technology-limited')
RAPHE = ('63db7ed7-7790-4789-b791-7a8991ea8339', 'Raphe mPhibr Private Limited', 'raphe-mphibr-private-limited')

# (drop_id, drop_name, keep, player_slug_or_None)
MERGES = [
    ('165fcd33-6a81-4156-9630-51694a84cfcc', 'ideaForge Technology Ltd', IDEAFORGE, 'ideaforge-technology-ltd'),
    ('62551d56-9f92-4636-9582-d16c0a346495', 'ideaForge', IDEAFORGE, None),
    ('c6baba23-533b-49a1-b6d8-79f793e936c5', 'ideaForge', IDEAFORGE, None),
    ('42c3405b-f882-42fa-a8de-30e68ae1f27f', 'Raphe mPhibr Pvt Ltd', RAPHE, 'raphe-mphibr-pvt-ltd'),
    ('996b2069-a5cb-4260-be60-ffbcc6bb6ea3', 'Raphe mPhibr', RAPHE, 'raphe-mphibr'),
    ('fa9cdce8-d94b-476c-8734-af9166ec6001', 'Raphe mPhibr Logistics', RAPHE, 'raphe-mphibr-logistics'),
]

# Unsourced PIL-6 edges on a duplicate ideaForge row (no primary_source_id, implausible:
# ideaForge is not a Su-30MKI or pressure-switch supplier). Deleted rather than migrated —
# the exports ignore valid_to, so retiring them would still publish them.
BAD_EDGES = [
    ('4f175a06-1e57-4ad3-8e6b-da0ae82c633a', 'ideaForge supplies_to DIFFERENTIAL PRESSURE SWITCH'),
    ('e1150baa-82c2-4230-b7aa-7ab575814718', 'ideaForge supplies_to Su-30MKI'),
]


def write_sql():
    L = ['-- SID duplicate merge — ideaForge x3, Raphe mPhibr x3 -> canonical records.',
         '-- Generated by scripts/sid-merge-duplicates.py. Safe to re-run.', 'begin;', '']
    L.append('-- 1. Drop unsourced, implausible edges on a duplicate (not migrated to the survivor).')
    for rid, label in BAD_EDGES:
        L.append(f"delete from sid.relationships where relationship_id = '{rid}';  -- {label}")
    L.append('')
    L.append('-- 2. Merge duplicates (sid.merge_entity: re-point edges, alias old name, mark merged).')
    for drop, name, keep, _ in MERGES:
        L.append(f"select sid.merge_entity('{keep[0]}', '{drop}');  -- {name} -> {keep[1]}")
    L += ['', 'commit;', '',
          '-- Verify (expect 6 merged rows, 0 live edges on them):',
          '-- select canonical_name, status, merged_into from sid.entities where entity_id in (' +
          ', '.join(f"'{m[0]}'" for m in MERGES) + ');',
          '-- select count(*) from sid.relationships where source_entity_id in (' +
          ', '.join(f"'{m[0]}'" for m in MERGES) + ') or target_entity_id in (' +
          ', '.join(f"'{m[0]}'" for m in MERGES) + ');', '']
    os.makedirs(os.path.dirname(SQL), exist_ok=True)
    open(SQL, 'w', encoding='utf-8').write('\n'.join(L))


def patch_atlas():
    a = json.load(open(ATLAS, encoding='utf-8'))
    drop = {m[0]: m[2] for m in MERGES}
    before_p, before_r = len(a['players']), len(a['relationships'])
    a['players'] = [p for p in a['players'] if p['id'] not in drop]
    bad = {'Su-30MKI', 'DIFFERENTIAL PRESSURE SWITCH'}
    seen, rels = set(), []
    for r in a['relationships']:
        if r.get('source') == 'ideaForge' and r.get('target') in bad:
            continue
        for end in ('source', 'target'):
            k = drop.get(r.get(f'{end}_id'))
            if k:
                r[f'{end}_id'], r[end] = k[0], k[1]
        if r.get('source_id') and r.get('source_id') == r.get('target_id'):
            continue
        key = (r.get('source_id'), r.get('target_id'), r.get('type'))
        if key in seen:
            continue
        seen.add(key)
        rels.append(r)
    a['relationships'] = rels
    with open(ATLAS, 'w', encoding='utf-8') as f:
        json.dump(a, f, ensure_ascii=False, indent=1)
        f.write('\n')
    return before_p - len(a['players']), before_r - len(rels)


def patch_redirects():
    txt = open(REDIRECTS, encoding='utf-8').read()
    added, new = 0, []
    for _, _, keep, slug in MERGES:
        if not slug:
            continue
        dest = f'/research/players/{keep[2]}/'
        # existing /research/entities/<slug> rules pointed at the now-retired player page
        txt = txt.replace(f' /research/players/{slug}/ 301', f' {dest} 301')
        for src in (f'/research/players/{slug}', f'/research/players/{slug}/'):
            if not re.search(rf'^{re.escape(src)}\s', txt, re.M):
                new.append(f'{src} {dest} 301')
                added += 1
    if new:  # static rules must precede the dynamic section
        marker = '\n# ---- Dynamic redirects'
        block = '\n'.join(new) + '\n'
        txt = txt.replace(marker, '\n' + block + marker, 1) if marker in txt else txt.rstrip('\n') + '\n' + block
    open(REDIRECTS, 'w', encoding='utf-8').write(txt)
    return added


if __name__ == '__main__':
    write_sql()
    p, r = patch_atlas()
    n = patch_redirects()
    print(f'SQL -> {os.path.relpath(SQL, ROOT)}; atlas: -{p} players, -{r} relationships; redirects: +{n} rules')
