#!/usr/bin/env python3
"""
Merge duplicate SID semiconductor entities (CG Semi, Kaynes Semicon, India Chip, Micron Sanand ATMP,
Unimicron) into their canonical records. Company and facility records for the same project
(e.g. TSAT company vs Jagiroad plant, Tata fab vs Tata Semiconductor Manufacturing) are NOT
duplicates and are left alone.

Writes:
  data/sid-maintenance/merge_duplicates_2026-10-08_semiconductors.sql  (run in the n8ndb SQL editor)
and patches, to match what the next bake will export:
  app/research/_atlas.json  (drops the duplicate players, re-points / de-dupes their edges)
  public/_redirects         (retired player URLs -> canonical player page)

The SQL uses the existing sid.merge_entity(keep, drop): it re-points relationships
(deleting ones the survivor already has), keeps the dropped name as an alias of the
survivor, and marks the duplicate status='merged', merged_into=keep, is_watchlist=false.
Idempotent: merge_entity is a no-op on an already-merged row's (now empty) edges.
"""
import json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SQL = os.path.join(ROOT, 'data', 'sid-maintenance', 'merge_duplicates_2026-10-08_semiconductors.sql')
ATLAS = os.path.join(ROOT, 'app', 'research', '_atlas.json')
REDIRECTS = os.path.join(ROOT, 'public', '_redirects')

CG = ('94f7f151-82ff-46c2-bdaa-392e84a92a96', 'CG Semi Private Limited', 'cg-semi-private-limited')
KAYNES = ('70a1661f-2ca6-47e3-8470-4783f493a7c6', 'Kaynes Semicon Private Limited', 'kaynes-semicon-private-limited')
INDIACHIP = ('24982411-a4b0-4087-b41d-e29187d8225a', 'India Chip Pvt Ltd (HCL + Foxconn JV)', 'india-chip-pvt-ltd-hcl-foxconn-jv')
MICRON_ATMP = ('0cb0ffc1-8bd0-44eb-a58a-5186ad7ca6d4', 'Micron ATMP Sanand', 'micron-atmp-sanand')
UNIMICRON = ('ff43877a-4338-480b-874d-cbd093127253', 'Unimicron Technology Corporation', 'unimicron-technology-corporation')

# (drop_id, drop_name, keep, player_slug_or_None). Survivors follow earlier merges where one
# exists (CG Semi -> 94f7..., Kaynes -> 70a1..., Micron Sanand ATMP -> 0cb0...), so all
# aliases converge on one record.
MERGES = [
    ('3900267c-16b8-4500-b3ed-e40664203212', 'CG Semi Pvt Ltd (CG Power + Renesas JV)', CG, 'cg-semi-pvt-ltd-cg-power-renesas-jv'),
    ('1f345cf5-1184-4c88-acd7-073f11539966', 'Kaynes Semicon Pvt Ltd', KAYNES, 'kaynes-semicon-pvt-ltd'),
    ('76c99abc-086d-4ea8-a171-713841bb8ff9', 'India Chip (HCL-Foxconn JV)', INDIACHIP, 'india-chip-hcl-foxconn-jv'),
    ('9c06adf9-54cd-40f3-9a14-84362fb6982c', 'Micron Technology India — Sanand ATMP', MICRON_ATMP, 'micron-technology-india-sanand-atmp'),
    ('1c6e967f-6769-4da3-85ae-9862c43fadb6', 'Unimicron', UNIMICRON, 'unimicron'),
    ('12bf2319-3ede-4b6d-a59c-f85c5d9c92a9', 'Unimicron Technology', UNIMICRON, 'unimicron-technology'),
]

BAD_EDGES = []


def write_sql():
    L = ['-- SID duplicate merge — semiconductor records (CG Semi, Kaynes, India Chip, Micron ATMP, Unimicron x2).',
         '-- Generated by scripts/sid-merge-semiconductor-duplicates.py. Safe to re-run.', 'begin;', '']
    L.append('-- Merge duplicates (sid.merge_entity: re-point edges, alias old name, mark merged).')
    for drop, name, keep, _ in MERGES:
        L.append(f"select sid.merge_entity('{keep[0]}', '{drop}');  -- {name} -> {keep[1]}")
    L += ['', 'commit;', '',
          f'-- Verify (expect {len(MERGES)} merged rows, 0 live edges on them):',
          '-- select canonical_name, status, merged_into from sid.entities where entity_id in (' +
          ', '.join(f"'{m[0]}'" for m in MERGES) + ');',
          '-- select count(*) from sid.relationships where source_entity_id in (' +
          ', '.join(f"'{m[0]}'" for m in MERGES) + ') or target_entity_id in (' +
          ', '.join(f"'{m[0]}'" for m in MERGES) + ');', '']
    os.makedirs(os.path.dirname(SQL), exist_ok=True)
    open(SQL, 'w', encoding='utf-8').write('\n'.join(L))


def patch_atlas():
    a = json.load(open(ATLAS, encoding='utf-8'))
    drop = {m[0]: m[2] for m in MERGES}
    before_p, before_r = len(a['players']), len(a['relationships'])
    a['players'] = [p for p in a['players'] if p['id'] not in drop]
    seen, rels = set(), []
    for r in a['relationships']:
        for end in ('source', 'target'):
            k = drop.get(r.get(f'{end}_id'))
            if k:
                r[f'{end}_id'], r[end] = k[0], k[1]
        if r.get('source_id') and r.get('source_id') == r.get('target_id'):
            continue
        key = (r.get('source_id'), r.get('target_id'), r.get('type'))
        if key in seen:
            continue
        seen.add(key)
        rels.append(r)
    a['relationships'] = rels
    with open(ATLAS, 'w', encoding='utf-8') as f:
        json.dump(a, f, ensure_ascii=False, indent=1)
        f.write('\n')
    return before_p - len(a['players']), before_r - len(rels)


def patch_redirects():
    txt = open(REDIRECTS, encoding='utf-8').read()
    added, new = 0, []
    for _, _, keep, slug in MERGES:
        if not slug:
            continue
        dest = f'/research/players/{keep[2]}/'
        # existing /research/entities/<slug> rules pointed at the now-retired player page
        txt = txt.replace(f' /research/players/{slug}/ 301', f' {dest} 301')
        for src in (f'/research/players/{slug}', f'/research/players/{slug}/'):
            if not re.search(rf'^{re.escape(src)}\s', txt, re.M):
                new.append(f'{src} {dest} 301')
                added += 1
    if new:  # static rules must precede the dynamic section
        marker = '\n# ---- Dynamic redirects'
        block = '\n'.join(new) + '\n'
        txt = txt.replace(marker, '\n' + block + marker, 1) if marker in txt else txt.rstrip('\n') + '\n' + block
    open(REDIRECTS, 'w', encoding='utf-8').write(txt)
    return added


if __name__ == '__main__':
    write_sql()
    p, r = patch_atlas()
    n = patch_redirects()
    print(f'SQL -> {os.path.relpath(SQL, ROOT)}; atlas: -{p} players, -{r} relationships; redirects: +{n} rules')
