import type { AtlasGraphEdge, AtlasGraphEntity, AtlasScore } from './graph-types';

const UPDATED = '2026-07-02';

const source = {
  ismProjects: {
    title: 'Cabinet approval and industry reporting on India semiconductor projects',
    url: 'https://en.wikipedia.org/wiki/Electronics_and_semiconductor_manufacturing_industry_in_India',
    publisher: 'Compiled public sources',
    date: '2024-2026',
    evidenceLevel: 'single_source' as const,
  },
  asmlTata: {
    title: 'ASML to equip India first commercial chip fab',
    url: 'https://www.tomshardware.com/tech-industry/asml-partners-with-tata-electronics-to-equip-indias-first-commercial-semiconductor-fab',
    publisher: 'Tom\'s Hardware',
    date: '2026-05-17',
    evidenceLevel: 'single_source' as const,
  },
  criticalMineralsIndia: {
    title: 'India critical minerals list and Ministry of Mines coverage',
    url: 'https://en.wikipedia.org/wiki/Critical_raw_materials',
    publisher: 'Compiled public sources',
    date: '2023-2026',
    evidenceLevel: 'single_source' as const,
  },
  pliDrones: {
    title: 'Production Linked Incentive scheme coverage for drones and components',
    url: 'https://en.wikipedia.org/wiki/Production_Linked_Incentive_schemes_in_India',
    publisher: 'Compiled public sources',
    date: '2021-2026',
    evidenceLevel: 'single_source' as const,
  },
  irel: {
    title: 'IREL rare earth processing and product coverage',
    url: 'https://en.wikipedia.org/wiki/IREL_(India)',
    publisher: 'Compiled public sources',
    date: '2023-2026',
    evidenceLevel: 'single_source' as const,
  },
  fabReport: {
    title: 'Who Really Benefits from India\'s Fab Ecosystem?',
    url: 'https://labs.techadyant.com/reports/india-fab-ecosystem/',
    publisher: 'Techadyant Labs',
    date: '2026-05-20',
    evidenceLevel: 'verified' as const,
  },
  missingLinksReport: {
    title: 'India\'s Semiconductor Supply Chain Missing Links and Industrial Opportunity Surfaces',
    url: 'https://labs.techadyant.com/reports/india-semiconductor-supply-chain-missing-links/',
    publisher: 'Techadyant Labs',
    date: '2026-12-12',
    evidenceLevel: 'modelled' as const,
  },
  vendorSignal: {
    title: 'The vendor economy behind semiconductor fabs',
    url: 'https://labs.techadyant.com/signals/vendor-economy-behind-semiconductor-fabs/',
    publisher: 'Techadyant Labs',
    date: '2026-06-26',
    evidenceLevel: 'verified' as const,
  },
  dholeraWaterSignal: {
    title: 'The Dholera Water Signal',
    url: 'https://labs.techadyant.com/signals/dholera-water-signal/',
    publisher: 'Techadyant Labs',
    date: '2026-06-30',
    evidenceLevel: 'verified' as const,
  },
  osatSignal: {
    title: 'India\'s Hidden OSAT Bottleneck',
    url: 'https://labs.techadyant.com/signals/osat-bottleneck/',
    publisher: 'Techadyant Labs',
    date: '2026-05-24',
    evidenceLevel: 'verified' as const,
  },
  dronePropulsionReport: {
    title: 'India\'s Drone Propulsion Opportunity',
    url: 'https://labs.techadyant.com/reports/india-drone-propulsion-opportunity/',
    publisher: 'Techadyant Labs',
    date: '2026-06-14',
    evidenceLevel: 'verified' as const,
  },
  droneBatteryReport: {
    title: 'India\'s Drone Battery Ecosystem',
    url: 'https://labs.techadyant.com/reports/indias-drone-battery-ecosystem/',
    publisher: 'Techadyant Labs',
    date: '2026-06-11',
    evidenceLevel: 'verified' as const,
  },
  droneSensorsReport: {
    title: 'India Drone Sensors, Payloads & Imaging Systems Market',
    url: 'https://labs.techadyant.com/reports/india-drone-sensors-payloads-imaging-market/',
    publisher: 'Techadyant Labs',
    date: '2026-06-16',
    evidenceLevel: 'verified' as const,
  },
  mineralsReport: {
    title: 'Who Actually Captures the India-US Minerals Alliance?',
    url: 'https://labs.techadyant.com/reports/who-actually-captures-the-india-us-minerals-alliance/',
    publisher: 'Techadyant Labs',
    date: '2026-05-30',
    evidenceLevel: 'verified' as const,
  },
  jewarSignal: {
    title: 'Jewar Isn\'t Becoming an Airport City. It\'s Becoming an Electronics Ecosystem.',
    url: 'https://labs.techadyant.com/signals/jewar-electronics-manufacturing-ecosystem/',
    publisher: 'Techadyant Labs',
    date: '2026-06-29',
    evidenceLevel: 'verified' as const,
  },
  tradeInfrastructureSignal: {
    title: 'Container manufacturing is really a trade-infrastructure signal',
    url: 'https://labs.techadyant.com/signals/container-sovereignty-trade-infrastructure/',
    publisher: 'Techadyant Labs',
    date: '2026-07-13',
    evidenceLevel: 'single_source' as const,
  },
};

function score(
  industrialImportance: number,
  strategicImportance: number,
  localizationPotential: number,
  importDependency: number,
  technologyComplexity: number,
  capitalIntensity: number,
): AtlasScore[] {
  return [
    { key: 'industrialImportance', label: 'Industrial importance', value: industrialImportance },
    { key: 'strategicImportance', label: 'Strategic importance', value: strategicImportance },
    { key: 'localizationPotential', label: 'Localization potential', value: localizationPotential },
    { key: 'importDependency', label: 'Import dependency', value: importDependency },
    { key: 'technologyComplexity', label: 'Technology complexity', value: technologyComplexity },
    { key: 'capitalIntensity', label: 'Capital intensity', value: capitalIntensity },
  ];
}

function entity(input: Omit<AtlasGraphEntity, 'updatedAt' | 'sourceSystem'>): AtlasGraphEntity {
  return { ...input, updatedAt: UPDATED, sourceSystem: 'curated' };
}

export const curatedSeedEntities: AtlasGraphEntity[] = [
  entity({
    id: 'technology:semiconductor-wafer-fabrication',
    slug: 'semiconductor-wafer-fabrication',
    kind: 'technology',
    title: 'Semiconductor wafer fabrication',
    subtitle: 'Front-end semiconductor manufacturing',
    summary: 'Wafer fabrication is the front-end manufacturing process that converts silicon wafers into integrated circuits through deposition, lithography, etching, doping and metrology steps. India first commercial fab push is anchored by Tata Electronics at Dholera with PSMC technology support.',
    tags: ['Semiconductors', 'Front-end fab', 'Dholera', '28nm', '300mm'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Anchor India project', value: 'Tata Electronics semiconductor fab at Dholera, Gujarat', sourceTitle: source.asmlTata.title },
      { label: 'Reported design capacity', value: '50,000 wafer starts per month', sourceTitle: source.asmlTata.title },
      { label: 'Reported technology range', value: '110nm to 28nm process nodes', sourceTitle: source.asmlTata.title },
    ],
    metrics: [
      { label: 'Dholera fab investment', value: '$11 billion', sourceTitle: source.asmlTata.title },
      { label: 'Capacity', value: '50,000', unit: 'wafers/month', sourceTitle: source.asmlTata.title },
    ],
    scores: score(5, 5, 4, 5, 5, 5),
    sources: [source.asmlTata, source.ismProjects],
    href: '/research/entities/semiconductor-wafer-fabrication/',
  }),
  entity({
    id: 'manufacturing_process:photolithography',
    slug: 'photolithography',
    kind: 'manufacturing_process',
    title: 'Photolithography',
    subtitle: 'Patterning process',
    summary: 'Photolithography transfers circuit patterns onto wafers and is one of the hardest semiconductor process steps to localize because tools, resists, optics and process control are globally concentrated.',
    tags: ['Lithography', 'Semiconductor equipment', 'Photoresist'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'India dependency surface', value: 'Lithography tools and associated materials remain externally sourced for commercial fabs.', sourceTitle: source.asmlTata.title },
    ],
    scores: score(5, 5, 3, 5, 5, 5),
    sources: [source.asmlTata],
    href: '/research/entities/photolithography/',
  }),
  entity({
    id: 'technology:outsourced-semiconductor-assembly-and-test',
    slug: 'outsourced-semiconductor-assembly-and-test',
    kind: 'technology',
    title: 'Outsourced Semiconductor Assembly and Test',
    subtitle: 'OSAT / ATMP',
    summary: 'OSAT covers assembly, testing, marking and packaging of semiconductor devices. It is India most active near-term semiconductor manufacturing layer, with Micron, Tata Electronics, CG Power and Kaynes-linked projects clustered around Gujarat and Assam.',
    tags: ['OSAT', 'ATMP', 'Advanced packaging', 'Sanand', 'Jagiroad'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Known India cluster', value: 'Sanand, Dholera and Jagiroad are emerging as semiconductor packaging and fabrication nodes.', sourceTitle: source.ismProjects.title },
      { label: 'Reported Tata Assam capacity', value: '48 million chips per day assembled at planned scale', sourceTitle: source.ismProjects.title },
      { label: 'Reported Kaynes ATMP capacity', value: '6.3 million chips per day', sourceTitle: source.ismProjects.title },
    ],
    metrics: [
      { label: 'Tata Assam investment', value: 'Rs 27,000 crore', sourceTitle: source.ismProjects.title },
      { label: 'Kaynes ATMP investment', value: 'Rs 3,307 crore', sourceTitle: source.ismProjects.title },
    ],
    scores: score(5, 4, 5, 3, 4, 4),
    sources: [source.ismProjects],
    href: '/research/entities/outsourced-semiconductor-assembly-and-test/',
  }),
  entity({
    id: 'technology:advanced-semiconductor-packaging',
    slug: 'advanced-semiconductor-packaging',
    kind: 'technology',
    title: 'Advanced semiconductor packaging',
    subtitle: 'High-density chip integration',
    summary: 'Advanced packaging increases chip performance by integrating dies, substrates and interconnects after wafer fabrication. For India, it is a practical capture layer between chip design and full front-end fabrication.',
    tags: ['Advanced packaging', 'Substrates', 'Heterogeneous integration'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Opportunity', value: 'Packaging is closer to India current manufacturing base than EUV-class front-end tools.', sourceTitle: source.ismProjects.title },
    ],
    scores: score(5, 5, 5, 4, 5, 4),
    sources: [source.ismProjects],
    href: '/research/entities/advanced-semiconductor-packaging/',
  }),
  entity({
    id: 'material:silicon-wafers',
    slug: 'silicon-wafers',
    kind: 'material',
    title: 'Silicon wafers',
    subtitle: 'Semiconductor substrate',
    summary: 'Silicon wafers are the polished substrates on which integrated circuits are built. Commercial-scale wafer supply requires ultra-high purity feedstock, crystal growth, slicing, polishing and defect-control capabilities.',
    tags: ['Silicon', 'Wafers', 'Substrate', 'Semiconductor materials'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Role', value: 'Base substrate for mainstream silicon integrated circuits.' },
      { label: 'India dependency surface', value: 'Large-scale semiconductor-grade wafer production is not yet a mature domestic capability.' },
    ],
    scores: score(5, 5, 4, 5, 5, 5),
    sources: [source.ismProjects],
    href: '/research/entities/silicon-wafers/',
  }),
  entity({
    id: 'material:photoresist',
    slug: 'photoresist',
    kind: 'material',
    title: 'Photoresist',
    subtitle: 'Lithography chemical',
    summary: 'Photoresist is the light-sensitive chemical layer used to transfer circuit patterns during lithography. It is a small-volume but strategically critical material in semiconductor fabs.',
    tags: ['Photoresist', 'Semiconductor chemicals', 'Lithography'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Role', value: 'Pattern-transfer material for lithography.' },
      { label: 'Dependency type', value: 'High-purity specialty chemical with tight qualification requirements.' },
    ],
    scores: score(4, 5, 4, 5, 5, 3),
    sources: [source.asmlTata],
    href: '/research/entities/photoresist/',
  }),
  entity({
    id: 'material:electronic-specialty-gases',
    slug: 'electronic-specialty-gases',
    kind: 'material',
    title: 'Electronic specialty gases',
    subtitle: 'Fab consumables',
    summary: 'Electronic specialty gases are used in deposition, etch, cleaning and chamber processes. They are a backlinkable localization surface because fabs need reliable, high-purity local supply chains.',
    tags: ['Specialty gases', 'Fab consumables', 'Semiconductor materials'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Role', value: 'Process gases for deposition, etch, cleaning and chamber operations.' },
      { label: 'Opportunity', value: 'Local gas purification and distribution can reduce fab operating risk.' },
    ],
    scores: score(4, 4, 5, 4, 4, 3),
    sources: [source.ismProjects],
    href: '/research/entities/electronic-specialty-gases/',
  }),
  entity({
    id: 'product:power-management-ic',
    slug: 'power-management-ic',
    kind: 'product',
    title: 'Power management IC',
    subtitle: 'PMIC',
    summary: 'Power management ICs regulate, convert and distribute power inside electronic systems. They are one of the product categories reported for India Dholera fab portfolio.',
    tags: ['PMIC', 'Power electronics', 'Semiconductors'],
    corridors: ['semiconductors', 'defence', 'ai_infrastructure'],
    keyFacts: [
      { label: 'Dholera portfolio', value: 'Power management ICs are among reported target products.', sourceTitle: source.asmlTata.title },
    ],
    scores: score(5, 4, 4, 4, 4, 4),
    sources: [source.asmlTata],
    href: '/research/entities/power-management-ic/',
  }),
  entity({
    id: 'product:microcontroller',
    slug: 'microcontroller',
    kind: 'product',
    title: 'Microcontroller',
    subtitle: 'Embedded control chip',
    summary: 'Microcontrollers provide embedded control for vehicles, industrial equipment, drones, appliances and IoT devices. They are a strategic bridge between semiconductor fabs and India electronics manufacturing base.',
    tags: ['MCU', 'Embedded systems', 'Automotive electronics', 'Drones'],
    corridors: ['semiconductors', 'defence'],
    keyFacts: [
      { label: 'Dholera portfolio', value: 'Microcontrollers are among reported target products.', sourceTitle: source.asmlTata.title },
    ],
    scores: score(5, 4, 4, 4, 4, 4),
    sources: [source.asmlTata],
    href: '/research/entities/microcontroller/',
  }),
  entity({
    id: 'material:rare-earth-elements',
    slug: 'rare-earth-elements',
    kind: 'material',
    title: 'Rare earth elements',
    subtitle: 'Critical minerals group',
    summary: 'Rare earth elements underpin permanent magnets, motors, sensors and defence electronics. India has domestic mineral and processing activity through IREL, but high-performance magnet and downstream component capture remains a strategic gap.',
    tags: ['Rare earths', 'Critical minerals', 'Magnets', 'Motors'],
    corridors: ['critical_minerals', 'defence'],
    keyFacts: [
      { label: 'India actor', value: 'IREL is a public sector rare-earth processor in India.', sourceTitle: source.irel.title },
      { label: 'Downstream dependency', value: 'High-performance magnet and motor supply chains are strategic localization targets.' },
    ],
    scores: score(5, 5, 4, 5, 4, 4),
    sources: [source.irel, source.criticalMineralsIndia],
    href: '/research/entities/rare-earth-elements/',
  }),
  entity({
    id: 'material:neodymium-praseodymium',
    slug: 'neodymium-praseodymium',
    kind: 'material',
    title: 'Neodymium-praseodymium',
    subtitle: 'NdPr magnet input',
    summary: 'Neodymium and praseodymium are key inputs for high-strength permanent magnets used in electric motors, wind turbines, drones and precision actuators.',
    tags: ['NdPr', 'Rare earth magnets', 'Permanent magnets'],
    corridors: ['critical_minerals', 'defence'],
    keyFacts: [
      { label: 'Use case', value: 'Input for high-strength permanent magnets.' },
      { label: 'India relevance', value: 'IREL product coverage includes rare-earth oxides and compounds.', sourceTitle: source.irel.title },
    ],
    scores: score(5, 5, 4, 5, 4, 3),
    sources: [source.irel, source.criticalMineralsIndia],
    href: '/research/entities/neodymium-praseodymium/',
  }),
  entity({
    id: 'product:rare-earth-permanent-magnet',
    slug: 'rare-earth-permanent-magnet',
    kind: 'product',
    title: 'Rare earth permanent magnet',
    subtitle: 'High-strength magnet',
    summary: 'Rare earth permanent magnets convert critical mineral access into motor and actuator capability. They sit between NdPr material supply and strategic products such as drone motors, EV motors and wind turbines.',
    tags: ['Permanent magnets', 'NdFeB', 'Motors', 'Actuators'],
    corridors: ['critical_minerals', 'defence'],
    keyFacts: [
      { label: 'Strategic role', value: 'Turns rare-earth material availability into motor and actuator capability.' },
    ],
    scores: score(5, 5, 5, 5, 4, 4),
    sources: [source.irel],
    href: '/research/entities/rare-earth-permanent-magnet/',
  }),
  entity({
    id: 'manufacturing_process:reduction-diffusion-magnet-making',
    slug: 'reduction-diffusion-magnet-making',
    kind: 'manufacturing_process',
    title: 'Reduction-diffusion magnet making',
    subtitle: 'Rare-earth magnet process',
    summary: 'Reduction-diffusion is a route for making rare-earth magnet alloy. It is relevant to India because rare-earth processing has upstream presence while high-performance magnet manufacturing remains a localization target.',
    tags: ['Reduction diffusion', 'Magnet making', 'Rare earths'],
    corridors: ['critical_minerals'],
    keyFacts: [
      { label: 'Process role', value: 'Converts rare-earth compounds into magnet alloy pathways.', sourceTitle: source.irel.title },
    ],
    scores: score(4, 4, 4, 4, 4, 3),
    sources: [source.irel],
    href: '/research/entities/reduction-diffusion-magnet-making/',
  }),
  entity({
    id: 'product:drone-brushless-dc-motor',
    slug: 'drone-brushless-dc-motor',
    kind: 'product',
    title: 'Drone brushless DC motor',
    subtitle: 'Propulsion component',
    summary: 'Brushless DC motors convert magnet, copper winding, controller and bearing supply chains into drone propulsion. They are a practical localization surface for India drone manufacturing.',
    tags: ['Drone propulsion', 'BLDC motor', 'Magnets', 'Defence electronics'],
    corridors: ['defence', 'critical_minerals'],
    keyFacts: [
      { label: 'Dependency chain', value: 'Requires magnets, motor controllers, precision winding, bearings and quality testing.' },
      { label: 'Policy relevance', value: 'Drone components are covered in India PLI drone policy universe.', sourceTitle: source.pliDrones.title },
    ],
    scores: score(5, 5, 5, 4, 4, 3),
    sources: [source.pliDrones],
    href: '/research/entities/drone-brushless-dc-motor/',
  }),
  entity({
    id: 'product:flight-controller',
    slug: 'flight-controller',
    kind: 'product',
    title: 'Flight controller',
    subtitle: 'Drone control electronics',
    summary: 'A flight controller combines microcontrollers, inertial sensors, firmware and power electronics to stabilize and control unmanned aerial systems.',
    tags: ['Drone electronics', 'Flight controller', 'Embedded systems', 'Sensors'],
    corridors: ['defence', 'semiconductors'],
    keyFacts: [
      { label: 'Bill of materials', value: 'Microcontrollers, IMUs, barometers, power management and firmware integration.' },
      { label: 'Strategic role', value: 'Core control layer for autonomous and remotely piloted drones.' },
    ],
    scores: score(5, 5, 5, 4, 4, 2),
    sources: [source.pliDrones],
    href: '/research/entities/flight-controller/',
  }),
  entity({
    id: 'product:electro-optical-infrared-payload',
    slug: 'electro-optical-infrared-payload',
    kind: 'product',
    title: 'Electro-optical / infrared payload',
    subtitle: 'Drone sensor payload',
    summary: 'EO/IR payloads combine optics, image sensors, thermal detectors, stabilization and onboard processing for surveillance, mapping and targeting applications.',
    tags: ['EO/IR', 'Drone sensors', 'Image sensors', 'Defence'],
    corridors: ['defence', 'semiconductors'],
    keyFacts: [
      { label: 'Strategic dependency', value: 'Optics, thermal detectors and image-processing electronics determine high-end payload performance.' },
    ],
    scores: score(5, 5, 4, 5, 5, 3),
    sources: [source.pliDrones],
    href: '/research/entities/electro-optical-infrared-payload/',
  }),
  entity({
    id: 'product:lithium-ion-drone-battery-pack',
    slug: 'lithium-ion-drone-battery-pack',
    kind: 'product',
    title: 'Lithium-ion drone battery pack',
    subtitle: 'Energy storage component',
    summary: 'Drone battery packs combine imported or domestic cells, battery management electronics, thermal design and pack integration. Cell chemistry and BMS quality determine endurance, safety and payload capacity.',
    tags: ['Drone batteries', 'Lithium-ion', 'BMS', 'Energy storage'],
    corridors: ['defence', 'critical_minerals'],
    keyFacts: [
      { label: 'Dependency chain', value: 'Cell supply, BMS electronics, pack integration and thermal safety.' },
    ],
    scores: score(5, 4, 5, 4, 4, 3),
    sources: [source.criticalMineralsIndia],
    href: '/research/entities/lithium-ion-drone-battery-pack/',
  }),
  entity({
    id: 'material:lithium',
    slug: 'lithium',
    kind: 'material',
    title: 'Lithium',
    subtitle: 'Battery critical mineral',
    summary: 'Lithium is a core input for lithium-ion batteries used in drones, EVs and stationary storage. It is part of India critical-minerals strategic concern because cell supply chains are globally concentrated.',
    tags: ['Lithium', 'Battery minerals', 'Critical minerals'],
    corridors: ['critical_minerals', 'defence'],
    scores: score(5, 5, 4, 5, 4, 5),
    sources: [source.criticalMineralsIndia],
    href: '/research/entities/lithium/',
  }),
  entity({
    id: 'material:natural-graphite',
    slug: 'natural-graphite',
    kind: 'material',
    title: 'Natural graphite',
    subtitle: 'Battery anode material',
    summary: 'Natural graphite is a key anode material for lithium-ion batteries and is a strategic battery supply-chain input alongside lithium, nickel and cobalt.',
    tags: ['Graphite', 'Battery anode', 'Critical minerals'],
    corridors: ['critical_minerals'],
    scores: score(5, 4, 4, 5, 3, 4),
    sources: [source.criticalMineralsIndia],
    href: '/research/entities/natural-graphite/',
  }),
  entity({
    id: 'policy:india-semiconductor-mission',
    slug: 'india-semiconductor-mission',
    kind: 'policy',
    title: 'India Semiconductor Mission',
    subtitle: 'Semiconductor ecosystem policy',
    summary: 'India Semiconductor Mission is the government policy architecture supporting semiconductor fabs, display fabs, compound semiconductor and ATMP/OSAT projects.',
    tags: ['ISM', 'Semiconductor policy', 'MeitY'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Policy role', value: 'Supports semiconductor and display manufacturing ecosystem development.' },
      { label: 'Known project set', value: 'Front-end fab, OSAT/ATMP and compound semiconductor projects are being approved under the mission universe.', sourceTitle: source.ismProjects.title },
    ],
    scores: score(5, 5, 5, 1, 3, 5),
    sources: [source.ismProjects],
    href: '/research/entities/india-semiconductor-mission/',
  }),
  entity({
    id: 'policy:pli-scheme-for-drones-and-drone-components',
    slug: 'pli-scheme-for-drones-and-drone-components',
    kind: 'policy',
    title: 'PLI Scheme for Drones and Drone Components',
    subtitle: 'Drone manufacturing policy',
    summary: 'The PLI scheme for drones and drone components is a policy lever for domestic drone manufacturing, including airframes, propulsion, control electronics and payload integration.',
    tags: ['PLI', 'Drones', 'Drone components', 'Manufacturing policy'],
    corridors: ['defence'],
    keyFacts: [
      { label: 'Policy scope', value: 'Targets drones and drone component manufacturing.', sourceTitle: source.pliDrones.title },
    ],
    scores: score(4, 4, 5, 1, 2, 3),
    sources: [source.pliDrones],
    href: '/research/entities/pli-scheme-for-drones-and-drone-components/',
  }),
  entity({
    id: 'policy:critical-minerals-auction-and-list',
    slug: 'critical-minerals-auction-and-list',
    kind: 'policy',
    title: 'India critical minerals list and auctions',
    subtitle: 'Mineral security policy',
    summary: 'India critical-minerals policy identifies strategic minerals and pushes exploration, auctions and downstream processing to reduce supply-chain vulnerability in batteries, electronics, defence and clean-energy systems.',
    tags: ['Critical minerals', 'Auctions', 'Ministry of Mines', 'Mineral security'],
    corridors: ['critical_minerals'],
    keyFacts: [
      { label: 'Policy role', value: 'Defines and prioritizes minerals relevant to strategic industries.', sourceTitle: source.criticalMineralsIndia.title },
    ],
    scores: score(5, 5, 5, 1, 3, 4),
    sources: [source.criticalMineralsIndia],
    href: '/research/entities/critical-minerals-auction-and-list/',
  }),
  entity({
    id: 'supply_chain:semiconductor-front-end-fab-supply-chain',
    slug: 'semiconductor-front-end-fab-supply-chain',
    kind: 'supply_chain',
    title: 'Semiconductor front-end fab supply chain',
    subtitle: 'Wafer fabrication chain',
    summary: 'The front-end fab supply chain links silicon wafers, photoresists, specialty gases, lithography tools, process equipment, cleanroom infrastructure and skilled process engineering into chip production.',
    tags: ['Fab supply chain', 'Semiconductor equipment', 'Materials'],
    corridors: ['semiconductors'],
    scores: score(5, 5, 4, 5, 5, 5),
    sources: [source.asmlTata, source.ismProjects],
    href: '/research/entities/semiconductor-front-end-fab-supply-chain/',
  }),
  entity({
    id: 'supply_chain:semiconductor-osat-supply-chain',
    slug: 'semiconductor-osat-supply-chain',
    kind: 'supply_chain',
    title: 'Semiconductor OSAT supply chain',
    subtitle: 'Assembly, test and packaging chain',
    summary: 'The OSAT supply chain links wafer sort, dicing, die attach, wire bonding or flip-chip, substrates, encapsulation, final test and reliability qualification.',
    tags: ['OSAT', 'ATMP', 'Packaging substrates', 'Final test'],
    corridors: ['semiconductors'],
    scores: score(5, 4, 5, 3, 4, 4),
    sources: [source.ismProjects],
    href: '/research/entities/semiconductor-osat-supply-chain/',
  }),
  entity({
    id: 'supply_chain:drone-electronics-and-propulsion-supply-chain',
    slug: 'drone-electronics-and-propulsion-supply-chain',
    kind: 'supply_chain',
    title: 'Drone electronics and propulsion supply chain',
    subtitle: 'UAS component chain',
    summary: 'The drone electronics and propulsion chain connects microcontrollers, flight controllers, EO/IR payloads, BLDC motors, rare-earth magnets, batteries and embedded firmware.',
    tags: ['Drones', 'Propulsion', 'Flight controllers', 'EO/IR'],
    corridors: ['defence', 'semiconductors', 'critical_minerals'],
    scores: score(5, 5, 5, 4, 4, 3),
    sources: [source.pliDrones],
    href: '/research/entities/drone-electronics-and-propulsion-supply-chain/',
  }),
  entity({
    id: 'supply_chain:rare-earth-permanent-magnet-supply-chain',
    slug: 'rare-earth-permanent-magnet-supply-chain',
    kind: 'supply_chain',
    title: 'Rare earth permanent magnet supply chain',
    subtitle: 'Critical-minerals to motors chain',
    summary: 'The rare-earth magnet chain connects mineral separation, oxide production, NdPr alloy, magnet making, motor assembly and downstream applications in drones, EVs, wind turbines and defence systems.',
    tags: ['Rare earths', 'Magnets', 'Motors', 'Critical minerals'],
    corridors: ['critical_minerals', 'defence'],
    scores: score(5, 5, 5, 5, 4, 4),
    sources: [source.irel, source.criticalMineralsIndia],
    href: '/research/entities/rare-earth-permanent-magnet-supply-chain/',
  }),
  entity({
    id: 'opportunity_surface:semiconductor-grade-materials-localisation',
    slug: 'semiconductor-grade-materials-localisation',
    kind: 'opportunity_surface',
    title: 'Semiconductor-grade materials localisation',
    subtitle: 'Opportunity surface',
    summary: 'Local production, purification and qualification of wafers, specialty gases, wet chemicals and photoresists can reduce fab operating risk and create supplier depth around Dholera and Sanand.',
    tags: ['Opportunity surface', 'Fab materials', 'Supplier development'],
    corridors: ['semiconductors'],
    scores: score(5, 5, 5, 4, 4, 4),
    sources: [source.asmlTata, source.ismProjects],
    href: '/research/entities/semiconductor-grade-materials-localisation/',
  }),
  entity({
    id: 'opportunity_surface:osat-substrate-and-test-ecosystem',
    slug: 'osat-substrate-and-test-ecosystem',
    kind: 'opportunity_surface',
    title: 'OSAT substrate and test ecosystem',
    subtitle: 'Opportunity surface',
    summary: 'Packaging substrates, leadframes, test sockets, handlers, reliability labs and failure-analysis services are near-term supplier opportunities around India OSAT buildout.',
    tags: ['Opportunity surface', 'Packaging substrates', 'Test ecosystem'],
    corridors: ['semiconductors'],
    scores: score(5, 4, 5, 3, 4, 3),
    sources: [source.ismProjects],
    href: '/research/entities/osat-substrate-and-test-ecosystem/',
  }),
  entity({
    id: 'opportunity_surface:drone-propulsion-localisation',
    slug: 'drone-propulsion-localisation',
    kind: 'opportunity_surface',
    title: 'Drone propulsion localisation',
    subtitle: 'Opportunity surface',
    summary: 'Drone propulsion localization spans BLDC motors, propellers, ESCs, rare-earth magnets, winding, bearings, quality testing and firmware integration.',
    tags: ['Opportunity surface', 'Drone propulsion', 'Motors'],
    corridors: ['defence', 'critical_minerals'],
    scores: score(5, 5, 5, 4, 4, 3),
    sources: [source.pliDrones],
    href: '/research/entities/drone-propulsion-localisation/',
  }),
  entity({
    id: 'opportunity_surface:rare-earth-magnet-localisation',
    slug: 'rare-earth-magnet-localisation',
    kind: 'opportunity_surface',
    title: 'Rare earth magnet localisation',
    subtitle: 'Opportunity surface',
    summary: 'Rare-earth magnet localization turns upstream mineral and oxide capability into high-value components for motors, actuators, drones, EVs and wind energy.',
    tags: ['Opportunity surface', 'Rare earth magnets', 'Critical minerals'],
    corridors: ['critical_minerals', 'defence'],
    scores: score(5, 5, 5, 5, 4, 4),
    sources: [source.irel, source.criticalMineralsIndia],
    href: '/research/entities/rare-earth-magnet-localisation/',
  }),
  entity({
    id: 'state:gujarat',
    slug: 'gujarat',
    kind: 'state',
    title: 'Gujarat',
    subtitle: 'Semiconductor and electronics manufacturing state',
    summary: 'Gujarat is the anchor state for India first large semiconductor buildout, with Dholera and Sanand emerging as linked fab, OSAT, materials, water and vendor-economy nodes.',
    tags: ['Gujarat', 'Dholera', 'Sanand', 'Semiconductors', 'Industrial water'],
    corridors: ['semiconductors', 'critical_minerals'],
    keyFacts: [
      { label: 'Anchor nodes', value: 'Dholera and Sanand', sourceTitle: source.asmlTata.title },
      { label: 'Industrial constraint', value: 'Water, power, gases, logistics and vendor proximity determine capture beyond subsidy.', sourceTitle: source.dholeraWaterSignal.title },
    ],
    scores: score(5, 5, 5, 2, 3, 5),
    sources: [source.asmlTata, source.dholeraWaterSignal, source.vendorSignal],
    href: '/research/entities/gujarat/',
  }),
  entity({
    id: 'state:assam',
    slug: 'assam',
    kind: 'state',
    title: 'Assam',
    subtitle: 'OSAT and electronics assembly state',
    summary: 'Assam enters the semiconductor map through Tata Electronics planned assembly and test facility at Jagiroad, making workforce, logistics and supplier development the key second-order questions.',
    tags: ['Assam', 'Jagiroad', 'OSAT', 'Assembly and test'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Anchor project', value: 'Tata Electronics assembly and test facility at Jagiroad', sourceTitle: source.ismProjects.title },
      { label: 'Reported investment', value: 'Rs 27,000 crore', sourceTitle: source.ismProjects.title },
    ],
    metrics: [
      { label: 'Reported capacity', value: '48 million', unit: 'chips/day', sourceTitle: source.ismProjects.title },
    ],
    scores: score(4, 4, 5, 2, 3, 4),
    sources: [source.ismProjects, source.osatSignal],
    href: '/research/entities/assam/',
  }),
  entity({
    id: 'state:uttar-pradesh',
    slug: 'uttar-pradesh',
    kind: 'state',
    title: 'Uttar Pradesh',
    subtitle: 'Electronics manufacturing corridor',
    summary: 'Uttar Pradesh is relevant to the Atlas because the Jewar-Noida belt is moving from airport-led real estate logic toward electronics manufacturing, supplier clustering and logistics-linked industrial capability.',
    tags: ['Uttar Pradesh', 'Jewar', 'Noida', 'Electronics manufacturing'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Anchor thesis', value: 'Jewar-Noida can become an electronics ecosystem, not only an airport city.', sourceTitle: source.jewarSignal.title },
    ],
    scores: score(4, 4, 5, 2, 3, 4),
    sources: [source.jewarSignal],
    href: '/research/entities/uttar-pradesh/',
  }),
  entity({
    id: 'industrial_corridor:dholera-sanand-semiconductor-corridor',
    slug: 'dholera-sanand-semiconductor-corridor',
    kind: 'industrial_corridor',
    title: 'Dholera-Sanand semiconductor corridor',
    subtitle: 'Fab, OSAT and vendor corridor',
    summary: 'The Dholera-Sanand corridor links India front-end fab ambition with OSAT, packaging, water, gases, cleanroom services, logistics and supplier development. It is the first corridor where the full semiconductor vendor economy can become visible.',
    tags: ['Dholera', 'Sanand', 'Semiconductor corridor', 'Vendor economy'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Anchor fab', value: 'Tata Electronics Dholera fab', sourceTitle: source.asmlTata.title },
      { label: 'Nearby manufacturing node', value: 'Sanand OSAT and electronics cluster', sourceTitle: source.ismProjects.title },
    ],
    scores: score(5, 5, 5, 3, 4, 5),
    sources: [source.asmlTata, source.vendorSignal, source.dholeraWaterSignal],
    href: '/research/entities/dholera-sanand-semiconductor-corridor/',
  }),
  entity({
    id: 'industrial_corridor:jewar-noida-electronics-corridor',
    slug: 'jewar-noida-electronics-corridor',
    kind: 'industrial_corridor',
    title: 'Jewar-Noida electronics corridor',
    subtitle: 'Airport-linked electronics ecosystem',
    summary: 'The Jewar-Noida corridor is an emerging electronics-manufacturing geography where airport logistics, land, suppliers and state incentives can combine into component and systems assembly depth.',
    tags: ['Jewar', 'Noida', 'Electronics manufacturing', 'Logistics'],
    corridors: ['semiconductors'],
    scores: score(4, 4, 5, 2, 3, 4),
    sources: [source.jewarSignal],
    href: '/research/entities/jewar-noida-electronics-corridor/',
  }),
  entity({
    id: 'material:ultrapure-water',
    slug: 'ultrapure-water',
    kind: 'material',
    title: 'Ultrapure water',
    subtitle: 'Fab utility material',
    summary: 'Ultrapure water is a critical fab utility used for wafer cleaning and process control. Semiconductor corridors need reliable water sourcing, treatment, recycling and monitoring, making water a strategic industrial dependency rather than a generic utility.',
    tags: ['Ultrapure water', 'Fab utilities', 'Industrial water', 'Dholera'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Role', value: 'Wafer cleaning, rinsing and contamination control.' },
      { label: 'India signal', value: 'Dholera water availability and treatment are a semiconductor corridor constraint.', sourceTitle: source.dholeraWaterSignal.title },
    ],
    scores: score(5, 5, 5, 4, 4, 4),
    sources: [source.dholeraWaterSignal, source.missingLinksReport],
    href: '/research/entities/ultrapure-water/',
  }),
  entity({
    id: 'material:semiconductor-wet-chemicals',
    slug: 'semiconductor-wet-chemicals',
    kind: 'material',
    title: 'Semiconductor wet chemicals',
    subtitle: 'Fab process consumables',
    summary: 'Wet chemicals such as acids, solvents and cleaning chemistries are used throughout wafer processing. The industrial opportunity is not commodity chemical production but semiconductor-grade purification, packaging, logistics and qualification.',
    tags: ['Wet chemicals', 'Fab consumables', 'Chemical purification'],
    corridors: ['semiconductors'],
    keyFacts: [
      { label: 'Capture layer', value: 'Purification, packaging, handling and qualification matter more than bulk chemical output.', sourceTitle: source.vendorSignal.title },
    ],
    scores: score(4, 4, 5, 4, 4, 3),
    sources: [source.vendorSignal, source.missingLinksReport],
    href: '/research/entities/semiconductor-wet-chemicals/',
  }),
  entity({
    id: 'material:gallium-nitride',
    slug: 'gallium-nitride',
    kind: 'material',
    title: 'Gallium nitride',
    subtitle: 'Compound semiconductor material',
    summary: 'Gallium nitride is a wide-bandgap semiconductor material used in power electronics, RF devices, mini/micro-LEDs and high-efficiency systems. It is strategically relevant to India because compound semiconductors can build capability outside mainstream silicon logic fabs.',
    tags: ['GaN', 'Compound semiconductors', 'Power electronics', 'RF'],
    corridors: ['semiconductors', 'defence'],
    scores: score(5, 5, 4, 5, 5, 4),
    sources: [source.ismProjects, source.missingLinksReport],
    href: '/research/entities/gallium-nitride/',
  }),
  entity({
    id: 'material:silicon-carbide',
    slug: 'silicon-carbide',
    kind: 'material',
    title: 'Silicon carbide',
    subtitle: 'Wide-bandgap semiconductor material',
    summary: 'Silicon carbide is used in high-voltage, high-temperature power electronics for EVs, grid systems, industrial drives and defence electronics. It is a strategic materials and device-manufacturing opportunity surface.',
    tags: ['SiC', 'Power electronics', 'Wide-bandgap semiconductor'],
    corridors: ['semiconductors', 'critical_minerals'],
    scores: score(5, 5, 4, 5, 5, 5),
    sources: [source.criticalMineralsIndia, source.missingLinksReport],
    href: '/research/entities/silicon-carbide/',
  }),
  entity({
    id: 'material:dysprosium-terbium',
    slug: 'dysprosium-terbium',
    kind: 'material',
    title: 'Dysprosium-terbium',
    subtitle: 'Heavy rare-earth magnet additives',
    summary: 'Dysprosium and terbium are heavy rare-earth inputs used to improve high-temperature performance in permanent magnets. They are small-volume but high-leverage dependencies for motors and defence-grade actuators.',
    tags: ['Dysprosium', 'Terbium', 'Heavy rare earths', 'Magnets'],
    corridors: ['critical_minerals', 'defence'],
    scores: score(5, 5, 3, 5, 4, 3),
    sources: [source.criticalMineralsIndia, source.mineralsReport],
    href: '/research/entities/dysprosium-terbium/',
  }),
  entity({
    id: 'product:electronic-speed-controller',
    slug: 'electronic-speed-controller',
    kind: 'product',
    title: 'Electronic speed controller',
    subtitle: 'Drone propulsion electronics',
    summary: 'Electronic speed controllers regulate BLDC motor speed and torque in drones. They connect semiconductor power devices, firmware, thermal design and motor-control algorithms to propulsion performance.',
    tags: ['ESC', 'Drone propulsion', 'Power electronics', 'Motor control'],
    corridors: ['defence', 'semiconductors'],
    keyFacts: [
      { label: 'System role', value: 'Controls BLDC motors and converts battery power into propulsion response.' },
      { label: 'Dependency layer', value: 'Power semiconductors, firmware and thermal design quality determine reliability.' },
    ],
    scores: score(5, 5, 5, 4, 4, 3),
    sources: [source.dronePropulsionReport],
    href: '/research/entities/electronic-speed-controller/',
  }),
  entity({
    id: 'product:inertial-measurement-unit',
    slug: 'inertial-measurement-unit',
    kind: 'product',
    title: 'Inertial measurement unit',
    subtitle: 'Drone navigation sensor',
    summary: 'An inertial measurement unit combines accelerometers and gyroscopes to estimate motion and orientation. In drones, IMUs are foundational for flight stabilization, navigation and autonomy.',
    tags: ['IMU', 'MEMS sensors', 'Drone navigation', 'Flight control'],
    corridors: ['defence', 'semiconductors'],
    scores: score(5, 5, 4, 5, 5, 3),
    sources: [source.droneSensorsReport],
    href: '/research/entities/inertial-measurement-unit/',
  }),
  entity({
    id: 'product:gnss-module',
    slug: 'gnss-module',
    kind: 'product',
    title: 'GNSS module',
    subtitle: 'Positioning component',
    summary: 'GNSS modules provide satellite-positioning capability for drones, vehicles and industrial systems. Their strategic relevance increases when paired with anti-jam, spoofing detection and domestic navigation augmentation.',
    tags: ['GNSS', 'Navigation', 'Drones', 'Positioning'],
    corridors: ['defence', 'semiconductors'],
    scores: score(4, 5, 4, 4, 4, 2),
    sources: [source.droneSensorsReport],
    href: '/research/entities/gnss-module/',
  }),
  entity({
    id: 'product:battery-management-system',
    slug: 'battery-management-system',
    kind: 'product',
    title: 'Battery management system',
    subtitle: 'Battery electronics',
    summary: 'A battery management system monitors cells, balances charge, manages thermal and safety limits, and communicates pack status to the drone or vehicle control stack.',
    tags: ['BMS', 'Battery electronics', 'Drone batteries', 'Power management'],
    corridors: ['defence', 'semiconductors', 'critical_minerals'],
    scores: score(5, 4, 5, 3, 4, 2),
    sources: [source.droneBatteryReport],
    href: '/research/entities/battery-management-system/',
  }),
  entity({
    id: 'product:thermal-imaging-core',
    slug: 'thermal-imaging-core',
    kind: 'product',
    title: 'Thermal imaging core',
    subtitle: 'EO/IR payload component',
    summary: 'Thermal imaging cores combine infrared detectors, optics, signal processing and calibration. They are a high-value dependency inside surveillance drones and defence sensing payloads.',
    tags: ['Thermal imaging', 'EO/IR', 'Infrared detector', 'Drone payloads'],
    corridors: ['defence', 'semiconductors'],
    scores: score(5, 5, 4, 5, 5, 3),
    sources: [source.droneSensorsReport],
    href: '/research/entities/thermal-imaging-core/',
  }),
  entity({
    id: 'product:packaging-substrate',
    slug: 'packaging-substrate',
    kind: 'product',
    title: 'Packaging substrate',
    subtitle: 'Semiconductor package input',
    summary: 'Packaging substrates provide interconnect between silicon dies and printed circuit boards. Substrate capability is a major bottleneck in advanced packaging and a natural supplier-development target for India OSAT ecosystem.',
    tags: ['Packaging substrate', 'Advanced packaging', 'OSAT', 'Interconnect'],
    corridors: ['semiconductors'],
    scores: score(5, 5, 5, 5, 5, 4),
    sources: [source.osatSignal, source.missingLinksReport],
    href: '/research/entities/packaging-substrate/',
  }),
  entity({
    id: 'manufacturing_process:wafer-dicing',
    slug: 'wafer-dicing',
    kind: 'manufacturing_process',
    title: 'Wafer dicing',
    subtitle: 'OSAT process',
    summary: 'Wafer dicing separates processed wafers into individual dies before assembly. It is a precision process where yield, contamination control and handling determine downstream package quality.',
    tags: ['Wafer dicing', 'OSAT', 'Assembly process'],
    corridors: ['semiconductors'],
    scores: score(4, 3, 5, 2, 3, 3),
    sources: [source.osatSignal],
    href: '/research/entities/wafer-dicing/',
  }),
  entity({
    id: 'manufacturing_process:die-attach',
    slug: 'die-attach',
    kind: 'manufacturing_process',
    title: 'Die attach',
    subtitle: 'OSAT process',
    summary: 'Die attach bonds semiconductor dies to a substrate or leadframe. Materials, thermal control and placement accuracy affect package reliability.',
    tags: ['Die attach', 'OSAT', 'Packaging'],
    corridors: ['semiconductors'],
    scores: score(4, 3, 5, 2, 3, 3),
    sources: [source.osatSignal],
    href: '/research/entities/die-attach/',
  }),
  entity({
    id: 'manufacturing_process:wire-bonding',
    slug: 'wire-bonding',
    kind: 'manufacturing_process',
    title: 'Wire bonding',
    subtitle: 'Semiconductor packaging process',
    summary: 'Wire bonding connects dies to package leads or substrates using fine metal wires. It remains central to many mature package types and is a practical capability layer for India OSAT buildout.',
    tags: ['Wire bonding', 'OSAT', 'Packaging'],
    corridors: ['semiconductors'],
    scores: score(4, 3, 5, 2, 3, 3),
    sources: [source.osatSignal],
    href: '/research/entities/wire-bonding/',
  }),
  entity({
    id: 'manufacturing_process:flip-chip-packaging',
    slug: 'flip-chip-packaging',
    kind: 'manufacturing_process',
    title: 'Flip-chip packaging',
    subtitle: 'Advanced packaging process',
    summary: 'Flip-chip packaging connects dies face-down to substrates through bumps, enabling higher interconnect density than wire bonding. It is a bridge from conventional OSAT toward advanced packaging.',
    tags: ['Flip-chip', 'Advanced packaging', 'Interconnect'],
    corridors: ['semiconductors'],
    scores: score(5, 5, 4, 4, 5, 4),
    sources: [source.osatSignal, source.missingLinksReport],
    href: '/research/entities/flip-chip-packaging/',
  }),
  entity({
    id: 'manufacturing_process:semiconductor-final-test',
    slug: 'semiconductor-final-test',
    kind: 'manufacturing_process',
    title: 'Semiconductor final test',
    subtitle: 'OSAT quality process',
    summary: 'Final test screens packaged semiconductors for function, performance and reliability. Test handlers, sockets, fixtures, ATE programs and failure analysis form a supplier ecosystem around OSAT plants.',
    tags: ['Final test', 'ATE', 'Reliability', 'Failure analysis'],
    corridors: ['semiconductors'],
    scores: score(5, 4, 5, 3, 4, 3),
    sources: [source.osatSignal, source.vendorSignal],
    href: '/research/entities/semiconductor-final-test/',
  }),
  entity({
    id: 'opportunity_surface:fab-water-recycling-and-treatment',
    slug: 'fab-water-recycling-and-treatment',
    kind: 'opportunity_surface',
    title: 'Fab water recycling and treatment',
    subtitle: 'Opportunity surface',
    summary: 'Fab water recycling and treatment is an industrial opportunity around semiconductor corridors because water resilience affects permitting, uptime, local trust and long-term operating cost.',
    tags: ['Water recycling', 'Ultrapure water', 'Dholera', 'Fab utilities'],
    corridors: ['semiconductors'],
    scores: score(5, 5, 5, 3, 4, 4),
    sources: [source.dholeraWaterSignal],
    href: '/research/entities/fab-water-recycling-and-treatment/',
  }),
  entity({
    id: 'opportunity_surface:drone-sensor-payload-localisation',
    slug: 'drone-sensor-payload-localisation',
    kind: 'opportunity_surface',
    title: 'Drone sensor payload localisation',
    subtitle: 'Opportunity surface',
    summary: 'Drone payload localization spans EO/IR cores, gimbals, stabilization, image processing, embedded AI and ruggedized integration. It is a higher-value opportunity than airframe assembly.',
    tags: ['Drone payloads', 'EO/IR', 'Sensors', 'Embedded AI'],
    corridors: ['defence', 'semiconductors'],
    scores: score(5, 5, 5, 5, 5, 3),
    sources: [source.droneSensorsReport],
    href: '/research/entities/drone-sensor-payload-localisation/',
  }),
  entity({
    id: 'opportunity_surface:jewar-electronics-supplier-cluster',
    slug: 'jewar-electronics-supplier-cluster',
    kind: 'opportunity_surface',
    title: 'Jewar electronics supplier cluster',
    subtitle: 'Opportunity surface',
    summary: 'Jewar electronics supplier clustering is an opportunity surface where logistics, airport proximity, Noida manufacturing, component suppliers and state industrial policy can converge into a durable electronics ecosystem.',
    tags: ['Jewar', 'Electronics suppliers', 'Airport logistics', 'Noida'],
    corridors: ['semiconductors'],
    scores: score(4, 4, 5, 2, 3, 4),
    sources: [source.jewarSignal],
    href: '/research/entities/jewar-electronics-supplier-cluster/',
  }),
  entity({
    id: 'supply_chain:container-manufacturing-supply-chain',
    slug: 'container-manufacturing-supply-chain',
    kind: 'supply_chain',
    title: 'Container manufacturing supply chain',
    subtitle: 'Trade-infrastructure chain',
    summary: 'The container manufacturing chain links weathering steel, structural fabrication, marine coatings, corner castings, locking systems, seals, inspection, certification, repair yards, leasing pools, ports, rail freight and export logistics into a single trade-infrastructure capability.',
    tags: ['Containers', 'Trade infrastructure', 'Ports', 'Rail freight', 'Logistics'],
    corridors: ['ai_infrastructure', 'defence', 'critical_minerals'],
    keyFacts: [
      { label: 'Strategic role', value: 'Containers are standardised trade infrastructure, not only fabricated steel boxes.', sourceTitle: source.tradeInfrastructureSignal.title },
      { label: 'Opportunity shift', value: 'Higher-value capture sits in specialised containers, components, repair, leasing and digital tracking.', sourceTitle: source.tradeInfrastructureSignal.title },
    ],
    scores: score(5, 5, 5, 4, 4, 4),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/container-manufacturing-supply-chain/',
  }),
  entity({
    id: 'product:specialised-shipping-container',
    slug: 'specialised-shipping-container',
    kind: 'product',
    title: 'Specialised shipping container',
    subtitle: 'High-value container platform',
    summary: 'Specialised containers include reefers, tank containers, chemical and hazardous-goods boxes, defence modules, battery transport containers, modular hospitals and containerised data-centre or edge-compute units. They move container manufacturing from commodity dry boxes toward engineered platforms.',
    tags: ['Reefer containers', 'Tank containers', 'Defence logistics', 'Containerised data centres'],
    corridors: ['ai_infrastructure', 'defence'],
    scores: score(5, 5, 5, 3, 5, 4),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/specialised-shipping-container/',
  }),
  entity({
    id: 'material:weathering-steel',
    slug: 'weathering-steel',
    kind: 'material',
    title: 'Weathering steel',
    subtitle: 'Container-grade steel input',
    summary: 'Weathering steel is a core input for shipping containers because corrosion resistance, structural consistency and price determine the economics of domestic dry-box and specialised-container manufacturing.',
    tags: ['Corten steel', 'Container steel', 'Steel ecosystem', 'Corrosion resistance'],
    corridors: ['critical_minerals'],
    scores: score(4, 4, 4, 4, 3, 3),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/weathering-steel/',
  }),
  entity({
    id: 'material:marine-grade-coatings',
    slug: 'marine-grade-coatings',
    kind: 'material',
    title: 'Marine-grade coatings',
    subtitle: 'Corrosion-protection layer',
    summary: 'Marine-grade coatings protect containers, ship-repair equipment and port-adjacent assets from corrosion. They are a supplier-development surface around container manufacturing, ports and coastal industrial clusters.',
    tags: ['Coatings', 'Corrosion protection', 'Ports', 'Container repair'],
    corridors: ['critical_minerals'],
    scores: score(4, 4, 5, 3, 4, 3),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/marine-grade-coatings/',
  }),
  entity({
    id: 'product:container-corner-casting',
    slug: 'container-corner-casting',
    kind: 'product',
    title: 'Container corner casting',
    subtitle: 'ISO container fitting',
    summary: 'Corner castings are small but critical ISO fittings that allow containers to be lifted, stacked and locked across ships, ports, rail wagons and trucks. They are an SME component opportunity inside domestic container manufacturing.',
    tags: ['Corner castings', 'ISO fittings', 'Container components', 'SME opportunity'],
    corridors: ['defence'],
    scores: score(4, 4, 5, 3, 3, 2),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/container-corner-casting/',
  }),
  entity({
    id: 'technology:reefer-container-systems',
    slug: 'reefer-container-systems',
    kind: 'technology',
    title: 'Reefer container systems',
    subtitle: 'Cold-chain container technology',
    summary: 'Reefer container systems combine insulated container bodies, refrigeration units, sensors, power interfaces and validation. They connect container manufacturing to India\'s pharma, seafood, food-processing and agricultural export chains.',
    tags: ['Reefer', 'Cold chain', 'Pharma exports', 'Seafood exports'],
    corridors: ['ai_infrastructure'],
    scores: score(5, 5, 5, 3, 5, 4),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/reefer-container-systems/',
  }),
  entity({
    id: 'opportunity_surface:trade-infrastructure-localisation',
    slug: 'trade-infrastructure-localisation',
    kind: 'opportunity_surface',
    title: 'Trade-infrastructure localisation',
    subtitle: 'Opportunity surface',
    summary: 'Trade-infrastructure localisation treats container manufacturing as the entry point into a broader ecosystem of components, repair yards, leasing pools, ICDs, multimodal logistics parks, rail freight interfaces, tracking systems and specialised container platforms.',
    tags: ['Trade sovereignty', 'Container manufacturing', 'Logistics parks', 'Export infrastructure'],
    corridors: ['ai_infrastructure', 'defence', 'critical_minerals'],
    scores: score(5, 5, 5, 4, 4, 4),
    sources: [source.tradeInfrastructureSignal],
    href: '/research/entities/trade-infrastructure-localisation/',
  }),
];

function edge(
  sourceId: string,
  targetId: string,
  kind: AtlasGraphEdge['kind'],
  label: string,
  summary?: string,
): AtlasGraphEdge {
  return {
    id: `curated:${sourceId}:${kind}:${targetId}`,
    sourceId,
    targetId,
    kind,
    label,
    summary,
    evidenceLevel: 'single_source',
  };
}

export const curatedSeedEdges: AtlasGraphEdge[] = [
  edge('policy:india-semiconductor-mission', 'technology:semiconductor-wafer-fabrication', 'enables', 'Enables', 'Policy support for front-end fab projects.'),
  edge('policy:india-semiconductor-mission', 'technology:outsourced-semiconductor-assembly-and-test', 'enables', 'Enables', 'Policy support for ATMP and OSAT projects.'),
  edge('supply_chain:semiconductor-front-end-fab-supply-chain', 'material:silicon-wafers', 'depends_on', 'Depends on'),
  edge('supply_chain:semiconductor-front-end-fab-supply-chain', 'material:photoresist', 'depends_on', 'Depends on'),
  edge('supply_chain:semiconductor-front-end-fab-supply-chain', 'material:electronic-specialty-gases', 'depends_on', 'Depends on'),
  edge('technology:semiconductor-wafer-fabrication', 'manufacturing_process:photolithography', 'depends_on', 'Depends on'),
  edge('technology:semiconductor-wafer-fabrication', 'product:power-management-ic', 'manufactures', 'Manufactures'),
  edge('technology:semiconductor-wafer-fabrication', 'product:microcontroller', 'manufactures', 'Manufactures'),
  edge('supply_chain:semiconductor-osat-supply-chain', 'technology:outsourced-semiconductor-assembly-and-test', 'belongs_to', 'Includes'),
  edge('technology:outsourced-semiconductor-assembly-and-test', 'technology:advanced-semiconductor-packaging', 'enables', 'Enables'),
  edge('opportunity_surface:semiconductor-grade-materials-localisation', 'material:silicon-wafers', 'depends_on', 'Targets'),
  edge('opportunity_surface:semiconductor-grade-materials-localisation', 'material:photoresist', 'depends_on', 'Targets'),
  edge('opportunity_surface:semiconductor-grade-materials-localisation', 'material:electronic-specialty-gases', 'depends_on', 'Targets'),
  edge('opportunity_surface:osat-substrate-and-test-ecosystem', 'supply_chain:semiconductor-osat-supply-chain', 'belongs_to', 'Builds around'),

  edge('policy:critical-minerals-auction-and-list', 'material:rare-earth-elements', 'enables', 'Prioritizes'),
  edge('material:rare-earth-elements', 'material:neodymium-praseodymium', 'supplies_to', 'Supplies'),
  edge('material:neodymium-praseodymium', 'product:rare-earth-permanent-magnet', 'supplies_to', 'Supplies'),
  edge('manufacturing_process:reduction-diffusion-magnet-making', 'product:rare-earth-permanent-magnet', 'enables', 'Enables'),
  edge('product:rare-earth-permanent-magnet', 'product:drone-brushless-dc-motor', 'supplies_to', 'Supplies'),
  edge('supply_chain:rare-earth-permanent-magnet-supply-chain', 'material:rare-earth-elements', 'depends_on', 'Depends on'),
  edge('supply_chain:rare-earth-permanent-magnet-supply-chain', 'product:rare-earth-permanent-magnet', 'manufactures', 'Produces'),
  edge('opportunity_surface:rare-earth-magnet-localisation', 'supply_chain:rare-earth-permanent-magnet-supply-chain', 'belongs_to', 'Builds around'),

  edge('policy:pli-scheme-for-drones-and-drone-components', 'supply_chain:drone-electronics-and-propulsion-supply-chain', 'enables', 'Enables'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:flight-controller', 'depends_on', 'Depends on'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:drone-brushless-dc-motor', 'depends_on', 'Depends on'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:electro-optical-infrared-payload', 'depends_on', 'Depends on'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:lithium-ion-drone-battery-pack', 'depends_on', 'Depends on'),
  edge('product:microcontroller', 'product:flight-controller', 'supplies_to', 'Supplies'),
  edge('material:lithium', 'product:lithium-ion-drone-battery-pack', 'supplies_to', 'Supplies'),
  edge('material:natural-graphite', 'product:lithium-ion-drone-battery-pack', 'supplies_to', 'Supplies'),
  edge('opportunity_surface:drone-propulsion-localisation', 'product:drone-brushless-dc-motor', 'depends_on', 'Targets'),
  edge('opportunity_surface:drone-propulsion-localisation', 'product:rare-earth-permanent-magnet', 'depends_on', 'Targets'),

  edge('state:gujarat', 'industrial_corridor:dholera-sanand-semiconductor-corridor', 'operates', 'Hosts', 'Gujarat hosts the Dholera-Sanand semiconductor corridor.'),
  edge('industrial_corridor:dholera-sanand-semiconductor-corridor', 'technology:semiconductor-wafer-fabrication', 'enables', 'Anchors'),
  edge('industrial_corridor:dholera-sanand-semiconductor-corridor', 'technology:outsourced-semiconductor-assembly-and-test', 'enables', 'Anchors'),
  edge('industrial_corridor:dholera-sanand-semiconductor-corridor', 'material:ultrapure-water', 'depends_on', 'Depends on'),
  edge('industrial_corridor:dholera-sanand-semiconductor-corridor', 'material:semiconductor-wet-chemicals', 'depends_on', 'Depends on'),
  edge('industrial_corridor:dholera-sanand-semiconductor-corridor', 'material:electronic-specialty-gases', 'depends_on', 'Depends on'),
  edge('state:assam', 'technology:outsourced-semiconductor-assembly-and-test', 'enables', 'Hosts'),
  edge('state:assam', 'supply_chain:semiconductor-osat-supply-chain', 'enables', 'Hosts'),
  edge('state:uttar-pradesh', 'industrial_corridor:jewar-noida-electronics-corridor', 'operates', 'Hosts'),
  edge('industrial_corridor:jewar-noida-electronics-corridor', 'opportunity_surface:jewar-electronics-supplier-cluster', 'enables', 'Enables'),

  edge('material:ultrapure-water', 'technology:semiconductor-wafer-fabrication', 'supplies_to', 'Supplies'),
  edge('material:semiconductor-wet-chemicals', 'technology:semiconductor-wafer-fabrication', 'supplies_to', 'Supplies'),
  edge('material:gallium-nitride', 'product:power-management-ic', 'used_in', 'Used in', 'GaN is a power-electronics material relevant to higher-efficiency devices.'),
  edge('material:silicon-carbide', 'product:power-management-ic', 'used_in', 'Used in', 'SiC is relevant to high-voltage power electronics and industrial drives.'),
  edge('material:dysprosium-terbium', 'product:rare-earth-permanent-magnet', 'supplies_to', 'Supplies', 'Heavy rare earths improve magnet high-temperature performance.'),
  edge('opportunity_surface:semiconductor-grade-materials-localisation', 'material:ultrapure-water', 'depends_on', 'Targets'),
  edge('opportunity_surface:semiconductor-grade-materials-localisation', 'material:semiconductor-wet-chemicals', 'depends_on', 'Targets'),
  edge('opportunity_surface:fab-water-recycling-and-treatment', 'material:ultrapure-water', 'depends_on', 'Targets'),
  edge('opportunity_surface:fab-water-recycling-and-treatment', 'industrial_corridor:dholera-sanand-semiconductor-corridor', 'belongs_to', 'Builds around'),

  edge('supply_chain:semiconductor-osat-supply-chain', 'manufacturing_process:wafer-dicing', 'depends_on', 'Includes'),
  edge('supply_chain:semiconductor-osat-supply-chain', 'manufacturing_process:die-attach', 'depends_on', 'Includes'),
  edge('supply_chain:semiconductor-osat-supply-chain', 'manufacturing_process:wire-bonding', 'depends_on', 'Includes'),
  edge('supply_chain:semiconductor-osat-supply-chain', 'manufacturing_process:flip-chip-packaging', 'depends_on', 'Includes'),
  edge('supply_chain:semiconductor-osat-supply-chain', 'manufacturing_process:semiconductor-final-test', 'depends_on', 'Includes'),
  edge('manufacturing_process:flip-chip-packaging', 'product:packaging-substrate', 'depends_on', 'Depends on'),
  edge('technology:advanced-semiconductor-packaging', 'product:packaging-substrate', 'depends_on', 'Depends on'),
  edge('opportunity_surface:osat-substrate-and-test-ecosystem', 'product:packaging-substrate', 'depends_on', 'Targets'),
  edge('opportunity_surface:osat-substrate-and-test-ecosystem', 'manufacturing_process:semiconductor-final-test', 'depends_on', 'Targets'),

  edge('product:battery-management-system', 'product:lithium-ion-drone-battery-pack', 'supplies_to', 'Controls'),
  edge('product:electronic-speed-controller', 'product:drone-brushless-dc-motor', 'supplies_to', 'Controls'),
  edge('product:flight-controller', 'product:electronic-speed-controller', 'controls', 'Controls'),
  edge('product:inertial-measurement-unit', 'product:flight-controller', 'supplies_to', 'Supplies'),
  edge('product:gnss-module', 'product:flight-controller', 'supplies_to', 'Supplies'),
  edge('product:thermal-imaging-core', 'product:electro-optical-infrared-payload', 'supplies_to', 'Supplies'),
  edge('opportunity_surface:drone-sensor-payload-localisation', 'product:electro-optical-infrared-payload', 'depends_on', 'Targets'),
  edge('opportunity_surface:drone-sensor-payload-localisation', 'product:thermal-imaging-core', 'depends_on', 'Targets'),
  edge('opportunity_surface:drone-propulsion-localisation', 'product:electronic-speed-controller', 'depends_on', 'Targets'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:electronic-speed-controller', 'depends_on', 'Depends on'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:inertial-measurement-unit', 'depends_on', 'Depends on'),
  edge('supply_chain:drone-electronics-and-propulsion-supply-chain', 'product:gnss-module', 'depends_on', 'Depends on'),

  edge('report:india-fab-ecosystem', 'technology:semiconductor-wafer-fabrication', 'evidenced_by', 'Evidence for'),
  edge('report:india-semiconductor-supply-chain-missing-links', 'opportunity_surface:semiconductor-grade-materials-localisation', 'evidenced_by', 'Evidence for'),
  edge('signal:vendor-economy-behind-semiconductor-fabs', 'opportunity_surface:semiconductor-grade-materials-localisation', 'evidenced_by', 'Evidence for'),
  edge('signal:dholera-water-signal', 'opportunity_surface:fab-water-recycling-and-treatment', 'evidenced_by', 'Evidence for'),
  edge('signal:osat-bottleneck', 'opportunity_surface:osat-substrate-and-test-ecosystem', 'evidenced_by', 'Evidence for'),
  edge('report:india-drone-propulsion-opportunity', 'opportunity_surface:drone-propulsion-localisation', 'evidenced_by', 'Evidence for'),
  edge('report:indias-drone-battery-ecosystem', 'product:lithium-ion-drone-battery-pack', 'evidenced_by', 'Evidence for'),
  edge('report:india-drone-sensors-payloads-imaging-market', 'opportunity_surface:drone-sensor-payload-localisation', 'evidenced_by', 'Evidence for'),
  edge('report:who-actually-captures-the-india-us-minerals-alliance', 'opportunity_surface:rare-earth-magnet-localisation', 'evidenced_by', 'Evidence for'),
  edge('signal:jewar-electronics-manufacturing-ecosystem', 'opportunity_surface:jewar-electronics-supplier-cluster', 'evidenced_by', 'Evidence for'),

  edge('supply_chain:container-manufacturing-supply-chain', 'material:weathering-steel', 'depends_on', 'Depends on'),
  edge('supply_chain:container-manufacturing-supply-chain', 'material:marine-grade-coatings', 'depends_on', 'Depends on'),
  edge('supply_chain:container-manufacturing-supply-chain', 'product:container-corner-casting', 'depends_on', 'Depends on'),
  edge('supply_chain:container-manufacturing-supply-chain', 'product:specialised-shipping-container', 'manufactures', 'Manufactures'),
  edge('product:specialised-shipping-container', 'technology:reefer-container-systems', 'depends_on', 'Depends on'),
  edge('opportunity_surface:trade-infrastructure-localisation', 'supply_chain:container-manufacturing-supply-chain', 'belongs_to', 'Builds around'),
  edge('opportunity_surface:trade-infrastructure-localisation', 'product:specialised-shipping-container', 'depends_on', 'Targets'),
  edge('signal:container-sovereignty-trade-infrastructure', 'opportunity_surface:trade-infrastructure-localisation', 'evidenced_by', 'Evidence for'),
];
