import Link from 'next/link';
import { getReport } from '../reports/data';

// Curated mapping of Atlas content -> full reports. Hand-reviewed so links stay
// meaningful (not domain auto-matching). Not regenerated by any sync script.
export const ECOSYSTEM_TO_REPORTS: Record<string, string[]> = {
  semiconductors: ['india-fab-ecosystem', 'semicon-2-0-opportunity-map', 'osat-and-the-packaging-frontier', 'india-semiconductor-supply-chain-missing-links'],
  critical_minerals: ['critical-minerals-strategic-roadmap', 'who-actually-captures-the-india-us-minerals-alliance'],
  ai_infrastructure: ['india-ai-industrial-transition-2026-2035', 'india-ai-power-infrastructure-gap', 'the-end-of-the-application-era'],
  defence: ['indias-unmanned-warfare-transformation', 'who-builds-indias-drones', 'india-battlefield-automation-gap', 'india-loitering-munitions-market', 'indian-navy-autonomous-maritime'],
  enterprise_software: ['the-sap-question', 'the-end-of-the-application-era'],
  ai_medtech: [],
};

export const ENTITY_TO_REPORTS: Record<string, string[]> = {
  // Rare earths & critical minerals
  'irel-india-limited': ['critical-minerals-strategic-roadmap'],
  'irel-rare-earth-permanent-magnet-plant-repm-visakhapatnam': ['critical-minerals-strategic-roadmap'],
  'khanij-bidesh-india-limited-kabil': ['critical-minerals-strategic-roadmap'],
  'vedanta-limited': ['critical-minerals-strategic-roadmap'],
  'national-aluminium-company-limited-nalco': ['critical-minerals-strategic-roadmap'],
  // Semiconductors
  'tata-electronics-private-limited': ['india-fab-ecosystem', 'semicon-2-0-opportunity-map'],
  'tata-semiconductor-fab-dholera': ['india-fab-ecosystem', 'dholera-semiconductor-supplier-ecosystem'],
  'micron-technology-india-sanand-atmp': ['india-fab-ecosystem', 'semicon-2-0-opportunity-map'],
  'landt-semiconductor-technologies': ['semicon-2-0-opportunity-map', 'osat-and-the-packaging-frontier'],
  'foxconn-india': ['india-fab-ecosystem'],
  'advanced-system-in-package-technologies-pvt-ltd-asip': ['osat-and-the-packaging-frontier'],
  'semiconductor-laboratory-scl-isro-meity': ['india-fab-ecosystem'],
  // AI / compute
  'vyoma-ai-data-centre-landt': ['india-ai-industrial-transition-2026-2035', 'india-ai-power-infrastructure-gap'],
  'adaniconnex': ['india-ai-power-infrastructure-gap'],
  // Defence & aerospace (players)
  'hindustan-aeronautics-limited': ['iaf-autonomous-air-power', 'who-builds-indias-drones'],
  'bharat-electronics-limited': ['india-battlefield-automation-gap'],
  'bharat-forge-limited-kalyani-strategic-systems': ['india-loitering-munitions-market'],
  'solar-industries-india-ltd': ['india-loitering-munitions-market'],
  'ideaforge-technology-ltd': ['who-builds-indias-drones'],
  'adani-defence-and-aerospace': ['who-builds-indias-drones', 'india-loitering-munitions-market'],
  // DRDO labs & drone companies (drones-uas mfr slugs)
  'drdo-centre-for-airborne-systems-cabs-mfr-031': ['iaf-autonomous-air-power'],
  'drdo-research-centre-imarat-rci-mfr-033': ['india-loitering-munitions-market'],
  'drdo-defence-electronics-research-laboratory-dlrl-mfr-032': ['india-battlefield-automation-gap'],
  'drdo-aeronautical-development-establishment-ade-mfr-007': ['indias-unmanned-warfare-transformation'],
  'bharat-dynamics-limited-bdl-mfr-012': ['india-loitering-munitions-market'],
  'bharat-forge-mfr-013': ['india-loitering-munitions-market'],
  'ideaforge-technology-ltd-mfr-014': ['who-builds-indias-drones'],
  'garuda-aerospace-pvt-ltd-mfr-015': ['who-builds-indias-drones'],
  'adani-defence-aerospace-mfr-017': ['who-builds-indias-drones'],
  'solar-industries-india-ltd-mfr-021': ['india-loitering-munitions-market'],
  'newspace-research-technologies-mfr-023': ['who-builds-indias-drones'],
};

/** Renders specific report links for a set of slugs, or null when none mapped. */
export function RelatedReportsLinks({ slugs }: { slugs?: string[] }) {
  const rs = (slugs || []).map((s) => ({ slug: s, title: getReport(s)?.title })).filter((x) => x.title);
  if (!rs.length) return null;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 7, alignItems: 'flex-start' }}>
      {rs.map(({ slug, title }) => (
        <Link key={slug} href={`/reports/${slug}/`} style={{ color: 'var(--link, #6cb0ff)', textDecoration: 'none', fontSize: 14, lineHeight: 1.5 }}>
          {title} →
        </Link>
      ))}
    </div>
  );
}
