-- SID duplicate merge — semiconductor records (CG Semi, Kaynes, India Chip, Micron ATMP, Unimicron x2).
-- Generated by scripts/sid-merge-semiconductor-duplicates.py. Safe to re-run.
begin;

-- Merge duplicates (sid.merge_entity: re-point edges, alias old name, mark merged).
select sid.merge_entity('94f7f151-82ff-46c2-bdaa-392e84a92a96', '3900267c-16b8-4500-b3ed-e40664203212');  -- CG Semi Pvt Ltd (CG Power + Renesas JV) -> CG Semi Private Limited
select sid.merge_entity('70a1661f-2ca6-47e3-8470-4783f493a7c6', '1f345cf5-1184-4c88-acd7-073f11539966');  -- Kaynes Semicon Pvt Ltd -> Kaynes Semicon Private Limited
select sid.merge_entity('24982411-a4b0-4087-b41d-e29187d8225a', '76c99abc-086d-4ea8-a171-713841bb8ff9');  -- India Chip (HCL-Foxconn JV) -> India Chip Pvt Ltd (HCL + Foxconn JV)
select sid.merge_entity('0cb0ffc1-8bd0-44eb-a58a-5186ad7ca6d4', '9c06adf9-54cd-40f3-9a14-84362fb6982c');  -- Micron Technology India — Sanand ATMP -> Micron ATMP Sanand
select sid.merge_entity('ff43877a-4338-480b-874d-cbd093127253', '1c6e967f-6769-4da3-85ae-9862c43fadb6');  -- Unimicron -> Unimicron Technology Corporation
select sid.merge_entity('ff43877a-4338-480b-874d-cbd093127253', '12bf2319-3ede-4b6d-a59c-f85c5d9c92a9');  -- Unimicron Technology -> Unimicron Technology Corporation

commit;

-- Verify (expect 6 merged rows, 0 live edges on them):
-- select canonical_name, status, merged_into from sid.entities where entity_id in ('3900267c-16b8-4500-b3ed-e40664203212', '1f345cf5-1184-4c88-acd7-073f11539966', '76c99abc-086d-4ea8-a171-713841bb8ff9', '9c06adf9-54cd-40f3-9a14-84362fb6982c', '1c6e967f-6769-4da3-85ae-9862c43fadb6', '12bf2319-3ede-4b6d-a59c-f85c5d9c92a9');
-- select count(*) from sid.relationships where source_entity_id in ('3900267c-16b8-4500-b3ed-e40664203212', '1f345cf5-1184-4c88-acd7-073f11539966', '76c99abc-086d-4ea8-a171-713841bb8ff9', '9c06adf9-54cd-40f3-9a14-84362fb6982c', '1c6e967f-6769-4da3-85ae-9862c43fadb6', '12bf2319-3ede-4b6d-a59c-f85c5d9c92a9') or target_entity_id in ('3900267c-16b8-4500-b3ed-e40664203212', '1f345cf5-1184-4c88-acd7-073f11539966', '76c99abc-086d-4ea8-a171-713841bb8ff9', '9c06adf9-54cd-40f3-9a14-84362fb6982c', '1c6e967f-6769-4da3-85ae-9862c43fadb6', '12bf2319-3ede-4b6d-a59c-f85c5d9c92a9');
