-- SID duplicate merge — ideaForge x3, Raphe mPhibr x3 -> canonical records.
-- Generated by scripts/sid-merge-duplicates.py. Safe to re-run.
begin;

-- 1. Drop unsourced, implausible edges on a duplicate (not migrated to the survivor).
delete from sid.relationships where relationship_id = '4f175a06-1e57-4ad3-8e6b-da0ae82c633a';  -- ideaForge supplies_to DIFFERENTIAL PRESSURE SWITCH
delete from sid.relationships where relationship_id = 'e1150baa-82c2-4230-b7aa-7ab575814718';  -- ideaForge supplies_to Su-30MKI

-- 2. Merge duplicates (sid.merge_entity: re-point edges, alias old name, mark merged).
select sid.merge_entity('080e8af1-025f-478f-bea8-26082bf32df1', '165fcd33-6a81-4156-9630-51694a84cfcc');  -- ideaForge Technology Ltd -> ideaForge Technology Limited
select sid.merge_entity('080e8af1-025f-478f-bea8-26082bf32df1', '62551d56-9f92-4636-9582-d16c0a346495');  -- ideaForge -> ideaForge Technology Limited
select sid.merge_entity('080e8af1-025f-478f-bea8-26082bf32df1', 'c6baba23-533b-49a1-b6d8-79f793e936c5');  -- ideaForge -> ideaForge Technology Limited
select sid.merge_entity('63db7ed7-7790-4789-b791-7a8991ea8339', '42c3405b-f882-42fa-a8de-30e68ae1f27f');  -- Raphe mPhibr Pvt Ltd -> Raphe mPhibr Private Limited
select sid.merge_entity('63db7ed7-7790-4789-b791-7a8991ea8339', '996b2069-a5cb-4260-be60-ffbcc6bb6ea3');  -- Raphe mPhibr -> Raphe mPhibr Private Limited
select sid.merge_entity('63db7ed7-7790-4789-b791-7a8991ea8339', 'fa9cdce8-d94b-476c-8734-af9166ec6001');  -- Raphe mPhibr Logistics -> Raphe mPhibr Private Limited

commit;

-- Verify (expect 6 merged rows, 0 live edges on them):
-- select canonical_name, status, merged_into from sid.entities where entity_id in ('165fcd33-6a81-4156-9630-51694a84cfcc', '62551d56-9f92-4636-9582-d16c0a346495', 'c6baba23-533b-49a1-b6d8-79f793e936c5', '42c3405b-f882-42fa-a8de-30e68ae1f27f', '996b2069-a5cb-4260-be60-ffbcc6bb6ea3', 'fa9cdce8-d94b-476c-8734-af9166ec6001');
-- select count(*) from sid.relationships where source_entity_id in ('165fcd33-6a81-4156-9630-51694a84cfcc', '62551d56-9f92-4636-9582-d16c0a346495', 'c6baba23-533b-49a1-b6d8-79f793e936c5', '42c3405b-f882-42fa-a8de-30e68ae1f27f', '996b2069-a5cb-4260-be60-ffbcc6bb6ea3', 'fa9cdce8-d94b-476c-8734-af9166ec6001') or target_entity_id in ('165fcd33-6a81-4156-9630-51694a84cfcc', '62551d56-9f92-4636-9582-d16c0a346495', 'c6baba23-533b-49a1-b6d8-79f793e936c5', '42c3405b-f882-42fa-a8de-30e68ae1f27f', '996b2069-a5cb-4260-be60-ffbcc6bb6ea3', 'fa9cdce8-d94b-476c-8734-af9166ec6001');
