// Curated signal -> report mapping. Each live signal is a short intelligence
// dispatch; the "full report" it naturally points to is listed here so the signal
// page can funnel readers to the product. Kept as an explicit, hand-reviewed map
// (not domain auto-matching) so links stay meaningful.
//
// This file is NOT regenerated by scripts/sync-cms-to-data.mjs.
export const SIGNAL_TO_REPORTS: Record<string, string[]> = {
  // --- Semiconductors ---
  'talent-constraint': ['india-fab-ecosystem'],
  'osat-bottleneck': ['osat-and-the-packaging-frontier'],
  'advanced-packaging-binding-constraint': ['osat-and-the-packaging-frontier'],
  'netrasemi-a2000-edge-ai-silicon': ['india-edge-ai-economy'],
  'talent-may-matter-more-than-subsidies': ['india-fab-ecosystem'],
  'vendor-economy-behind-semiconductor-fabs': ['india-fab-ecosystem'],
  'jewar-electronics-manufacturing-ecosystem': ['the-opportunity-beyond-the-fab'],
  'dholera-water-signal': ['water-behind-indias-semiconductor-ambitions'],
  'semicon-2-0-ecosystem-shift': ['semicon-2-0-opportunity-map'],
  'high-purity-minerals-for-semiconductors': ['critical-minerals-strategic-roadmap'],
  'marvell-india-semiconductor-design': ['semicon-2-0-opportunity-map'],
  'india-glass-substrate-frontier-entry': ['india-semiconductor-supply-chain-missing-links'],
  'asip-osat-visakhapatnam': ['osat-and-the-packaging-frontier'],
  'lt-semiconductor-technologies-osat-shift-india': ['osat-and-the-packaging-frontier'],
  'gujarat-chipin-extension-centre-vlsi-design-coe': ['semicon-2-0-opportunity-map'],
  'uttar-pradesh-lands-45000-crore-semiconductor-solar-investments': ['semicon-2-0-opportunity-map'],
  'pm-modi-5-8-semiconductor-plants-7-8-years': ['india-fab-ecosystem'],
  'aheesa-first-pass-silicon-vihaan-networking-soc': ['india-fab-ecosystem'],
  'three-indian-semiconductor-plants-live-ism-20-approved-semicon-india-2026': ['india-fab-ecosystem'],

  // --- AI infrastructure ---
  'visakhapatnam-coastal-ai': ['india-ai-industrial-transition-2026-2035'],
  'ai-corridor-competition': ['india-ai-industrial-transition-2026-2035'],
  'ai-opportunity-surfaces-india': ['india-ai-industrial-transition-2026-2035'],
  'real-constraint-behind-ai-infrastructure': ['india-ai-power-infrastructure-gap'],
  'indiaai-mission-gpu-compute-expansion': ['india-ai-industrial-transition-2026-2035'],
  'india-data-centre-capacity-surges-four-fold': ['india-ai-power-infrastructure-gap'],
  'lt-together-ai-nvidia-b300-ai-factory-chennai': ['india-ai-industrial-transition-2026-2035'],

  // --- Quantum / strategic tech ---
  'quantum-orders-industrial-policy': ['beyond-quantum-computing'],

  // --- Critical minerals & manufacturing dependencies ---
  'magnet-free-motors-rare-earth-value-chain': ['critical-minerals-strategic-roadmap'],
  'battery-materials-processing-india': ['critical-minerals-strategic-roadmap'],
  'refinery-equipment-technology-transfer': ['india-critical-manufacturing-dependencies'],
  'india-asia-mineral-processing-hub': ['critical-minerals-strategic-roadmap'],
  'mineral-security-to-processing-thesis': ['critical-minerals-strategic-roadmap'],
  'rare-earth-magnets-motors-chokepoint': ['critical-minerals-strategic-roadmap'],
  'hindustan-copper-uzbekistan-minerals-partnership': ['critical-minerals-strategic-roadmap'],
  'vedanta-punnam-manganese-block-andhra-pradesh': ['critical-minerals-strategic-roadmap'],
  'india-build-the-stack-not-assembly': ['india-critical-manufacturing-dependencies'],
  'critical-manufacturing-dependency-index-launch': ['india-critical-manufacturing-dependencies'],
  'india-manufacturing-chokepoints-cmdi': ['india-critical-manufacturing-dependencies'],
  'india-build-now-localisation-surfaces': ['india-critical-manufacturing-dependencies'],
  'india-pli-uneven-record-component-gap': ['india-critical-manufacturing-dependencies'],
  'india-state-manufacturing-capability-rankings': ['india-critical-manufacturing-dependencies'],
  'india-eight-structural-gaps-dependency': ['india-critical-manufacturing-dependencies'],
  'india-twelve-opportunity-zones-industrial-capital': ['india-critical-manufacturing-dependencies'],
  'india-critical-manufacturing-dependency-report-edition-1': ['india-critical-manufacturing-dependencies'],

  // --- Industrial infrastructure / logistics ---
  'indias-hidden-industrial-water-crisis': ['india-industrial-water-opportunity-map'],
  'container-sovereignty-trade-infrastructure': ['industrial-logistics-behind-manufacturing-india'],
  'msc-flags-off-first-import-rail-shipment-adani-icd-malur-bengaluru': ['industrial-logistics-behind-manufacturing-india'],

  // --- Defence / drones ---
  'india-indigenous-turbojet-engine': ['india-drone-propulsion-opportunity'],
  'india-uk-autonomous-systems-working-group': ['indias-unmanned-warfare-transformation'],
  'army-2715-logistic-drones-rfi': ['india-cargo-drone-market'],
  'lt-precision-engineering-drone-revenue-threefold-growth': ['who-builds-indias-drones'],
  'india-joins-france-fcas-sixth-generation-fighter-programme': ['iaf-autonomous-air-power'],
  'd-propulse-demonstrates-india-first-rotating-detonation-engine-trl5': ['india-drone-propulsion-opportunity'],
  'indian-navy-issues-rfi-ship-launched-loitering-munition-1000km-range': ['india-loitering-munitions-market'],
  'indian-air-force-pokhran-unmanned-systems-showcase-september-2026': ['indias-unmanned-warfare-transformation'],
  'izi-demonstrates-vana-tethered-drone-indian-army-5000-unit-procurement': ['who-builds-indias-drones'],
  'bel-600-crore-chitrakoot-defence-unit': ['india-battlefield-automation-gap'],
  'indian-army-orders-840-one-way-attack-drones-tata-nibe': ['india-loitering-munitions-market'],
  'divyastra-mk3-india-first-indigenous-jet-powered-loitering-munition': ['india-loitering-munitions-market'],
  'india-leases-two-mq-9b-seaguardian-indian-navy-indian-ocean-surveillance': ['indian-navy-autonomous-maritime'],
  'indian-army-orders-indrajaal-ranger-mobile-counter-drone-system': ['india-battlefield-automation-gap'],
};
